### ISSUE TITLE
 ArgumentError in Pics#index

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#112]
![ss](https://user-images.githubusercontent.com/19534210/91359734-ea891b80-e816-11ea-89ec-9049d0038a5a.png)
(I will convert the haml to erb later)
index.html.haml
```
- @pics.each do |pic|
  = link_to (image_tag pic.image.url(:medium)), pic
  %h2= link_to pic.title,pic
```
After adding **= link_to (image_tag pic.image.url(:medium)), pic** this error shows up, I can see the pictures perfectly and create and post with picture
![ror1](https://user-images.githubusercontent.com/19534210/91359949-61261900-e817-11ea-8294-82ba0b2751cd.png)

**Comment by sadmanahmed** [comment]
```
Started GET "/" for 127.0.0.1 at 2020-08-27 03:46:36 +0600
   (0.7ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by PicsController#index as HTML
  Rendering pics/index.html.haml within layouts/application
  Pic Load (0.8ms)  SELECT "pics".* FROM "pics" ORDER BY created_at DESC
  ↳ app/views/pics/index.html.haml:1
  Rendered pics/index.html.haml within layouts/application (Duration: 19.4ms | Allocations: 10141)
Completed 500 Internal Server Error in 30ms (ActiveRecord: 5.5ms | Allocations: 13350)


  
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    1: - @pics.each do |pic|
    2:   = link_to (image_tag pic.image.url(:medium)), pic
    3:   %h2= link_to pic.title,pic
  
app/views/pics/index.html.haml:2
app/views/pics/index.html.haml:1
```

**Comment by wasifhossain** [comment]
which version of Shrine are you using

**Comment by sadmanahmed** [comment]
gem "shrine", "~> 3.2"

**Comment by wasifhossain** [comment]
it looks like `pic.image.url` does not need any argument. can you try again without passing `:medium`

**Comment by sadmanahmed** [comment]
**SOLVED**
![ss](https://user-images.githubusercontent.com/19534210/91361153-8caa0300-e819-11ea-811e-6eb7287ba4da.png)

**Comment by sadmanahmed** [comment]
what is the difference in **image.url** vs **image_url** ( I tried both and ends up with same result and no error)

**Comment by wasifhossain** [comment]
there are aliases
