### ISSUE TITLE
Authenticate correct user

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#113]
The code perfectly working but the problem is here user 1 can edit/update user2's post and vice verca , so i want to add to commented line(the before action and the private method) but it throws away this error 
```
class PicsController < ApplicationController
before_action :find_pic, only: [:show,:edit,:update,:destroy,:upvote]
before_action :authenticate_user!,except: [:index,:show]
#before_action :correct_user, only: %i[edit update]

def index
  @pics = Pic.all.order("created_at DESC")
end

def show
end

def new
  @pic = current_user.pics.build
end

def create
  @pic = current_user.pics.build(pic_params)

  if @pic.save
    redirect_to @pic,notice: "Yesss! It is posted"
  else
    render 'new'
  end
end

def edit
end

def destroy
  @pic.destroy
  redirect_to root_path
end

def update
  if @pic.update(pic_params)
    redirect_to @pic, notice: "Congrats! Pic was updated!"
  else
    render 'edit'
  end
end

def upvote
    @pic.upvote_by current_user
    redirect_to @pic
  end

private
  def pic_params
    params.require(:pic).permit(:title,:description,:image)
  end

  def find_pic
    @pic = Pic.find(params[:id])
  end
  # def correct_user
  #   @user = User.find(params[:id])
  #   redirect_to(root_url) unless current_user?(@user)
  # end
end
```
![ss](https://user-images.githubusercontent.com/19534210/91507554-f6e4a580-e8f6-11ea-89ee-c2391777bff1.png)

I want to know how can fix this totally

**Comment by sadmanahmed** [comment]
Additional info : 
If you see, there is a fix and delete button are there. I don't want to show them there and also available those for the correct users. These buttons are open for all and anyone can delete anyone's post.
![ss](https://user-images.githubusercontent.com/19534210/91623213-535dc880-e9bc-11ea-91cb-4081eadf039f.png)

**Comment by wasifhossain** [comment]
@sadmanahmed  you need to apply the same logic to access pics (`current_user.pics`) in the `edit/update` actions as the way you did in `new/create` actions.

**Comment by wasifhossain** [comment]
regarding the error:
> Couldn't find User with 'id' = 10

the url that you are visiting is `/pics/10/edit`. so `params[:id]` would be 10, which is likely to be the id of some Pic, and definitely NOT for a User.

you can get access to the currently logged in user via `current_user`, which gets populated after successful execution of `authenticate_user!` helper, thanks to the Devise gem

**Comment by wasifhossain** [comment]
the way `find_pic` method is loading the pic from `params[:id]` is the reason why everyone is able to update any pic. if you want to restrict it to the user who owns that pic, then you need to update the pic lookup logic as
```rb
def find_pic
  @pic = current_user.pics.find_by(id: params[:id])
  return @pic if @pic

  flash[:alert] = 'Sorry! you are not allowed to perform the action.'
  redirect_to root_path
end
```

**Comment by wasifhossain** [comment]
with that fix in the pic lookup strategy, next you need to update the view logic to render the buttons (**Fix Pic/Delete**) only when the pic belongs to the current_user

a robust way to implement this logic is to use a well known gem for authorization, called `CanCanCan`

see how abilities can be checked for this case: https://github.com/CanCanCommunity/cancancan/#check-abilities
