### ISSUE TITLE
resolve git conflicts

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#114]
After run `git push`
There is an error

> ayub@ayub:~/alpha-blog$ git push
Username for 'https://github.com': ansary14
Password for 'https://ansary14@github.com': 
To https://github.com/ansary14/alpha-blog.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/ansary14/alpha-blog.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by ansary14-zz** [comment]
Then I visit GitHub issues and found related topics 
https://github.com/ormprog/rails_ama/issues/94#issuecomment-659085338

Following the above instructions
after run git pull origin master
result is

> ayub@ayub:~/alpha-blog$ git pull origin master
> remote: Enumerating objects: 103, done.
> remote: Counting objects: 100% (103/103), done.
> remote: Compressing objects: 100% (45/45), done.
> remote: Total 82 (delta 63), reused 55 (delta 36), pack-reused 0
> Unpacking objects: 100% (82/82), 8.46 KiB | 38.00 KiB/s, done.
> From https://github.com/ansary14/alpha-blog
>  * branch            master     -> FETCH_HEAD
>    358cb7f..20f6963  master     -> origin/master
> Auto-merging db/schema.rb
> CONFLICT (content): Merge conflict in db/schema.rb
> Automatic merge failed; fix conflicts and then commit the result.
>

**Comment by ansary14-zz** [comment]
Then I run `git status`
It shows

> ayub@ayub:~/alpha-blog$ git status
> On branch master
> Your branch and 'origin/master' have diverged,
> and have 2 and 9 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
> 
> You have unmerged paths.
>   (fix conflicts and run "git commit")
>   (use "git merge --abort" to abort the merge)
> 
> Unmerged paths:
>   (use "git add <file>..." to mark resolution)
> 	both modified:   db/schema.rb
> 
> no changes added to commit (use "git add" and/or "git commit -a")
>

**Comment by sadmanahmed** [comment]
what is the outcome of **git pull**?

**Comment by ansary14-zz** [comment]
The outcome of `git pull`
> ayub@ayub:~/alpha-blog$ git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by ansary14-zz** [comment]
Here is `schema.rb` file screenshot
![Screenshot from 2020-09-02 08-21-00](https://user-images.githubusercontent.com/33208962/91924787-68589580-ecf5-11ea-83e8-6bc40dd2f375.png)

**Comment by wasifhossain** [comment]
could you share the output of `git status`

**Comment by ansary14-zz** [comment]
output of `git status`

> ayub@ayub:~/alpha-blog$ git status
> On branch master
> Your branch and 'origin/master' have diverged,
> and have 2 and 9 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
> 
> You have unmerged paths.
>   (fix conflicts and run "git commit")
>   (use "git merge --abort" to abort the merge)
> 
> Unmerged paths:
>   (use "git add <file>..." to mark resolution)
> 	both modified:   db/schema.rb
> 
> no changes added to commit (use "git add" and/or "git commit -a")
>

**Comment by wasifhossain** [comment]
i see. so you have a conflict in 1 of your files
>Unmerged paths:
(use "git add ..." to mark resolution)
both modified: db/schema.rb

could you share lines between 13 to 17 (inclusive) from db/schema.rb (lines that are wrapped between <<<<< and >>>>>> )

**Comment by ansary14-zz** [comment]
![Screenshot from 2020-09-02 08-21-00](https://user-images.githubusercontent.com/33208962/92121147-c1bae480-ee1b-11ea-8af9-4dafbbfbdc6f.png)

**Comment by wasifhossain** [comment]
sorry i meant text; not as an image. need to copy lines from your sharing

**Comment by ansary14-zz** [comment]
```
<<<<<<< HEAD
ActiveRecord::Schema.define(version: 2020_08_21_132236) do
=======
ActiveRecord::Schema.define(version: 2020_07_28_141825) do
>>>>>>> 20f696346251aafa1bb968febd76f751f7765a67
```

**Comment by wasifhossain** [comment]
alright. you can see that any conflict in a file during a GIT operation is highlighted in a specific way, which basically has 2 parts:
1. `<our>` commit changes: section between `<<<<<<< HEAD` and `=======`
2. `<their>` commit changes: section between `=======` and `>>>>>>>`

by 'ours', we mean your local commit, while 'theirs' point to the remote commit.

now you have to decide which set of changes you would like to keep and which one to get rid from. 
once you have decided, remove the changes that you don't want along with lines containing special character-set `<<<<<<< HEAD`, `=======` and `>>>>>>>`

for your case of conflict, Rails uses a strategy to generate schema versions. most of the times, you would want to keep the latest version, `2020_08_21_132236` in this case.

so let's keep line 14 and remove the other lines, namely 16, along with the special character lines 13, 15 and 17

after removing the unwanted changes as I suggested, it would look like
```rb
ActiveRecord::Schema.define(version: 2020_08_21_132236) do
```

after that, you need to add this change to index, which you can do by running `git add <resolved file path with conflicts>`. for you case, it would be `git add db/schema.rb`

in this way, once you resolve all conflicts across files by following the strategy described above, you will see a message from `git status`, saying: `all conflicts resolved`. lets share the output at that point.

**Comment by ansary14-zz** [comment]
First I remove 13,15,16,17 line 

After running above command `git add db/schema.rb`
it shows nothing

then I run `git status`

> ayub@ayub:~/alpha-blog$ git add db/schema.rb
> ayub@ayub:~/alpha-blog$ git status
> On branch master
> Your branch and 'origin/master' have diverged,
> and have 2 and 9 different commits each, respectively.
>   (use "git pull" to merge the remote branch into yours)
> 
> All conflicts fixed but you are still merging.
>   (use "git commit" to conclude merge)
>

**Comment by wasifhossain** [comment]
everything went well so far. notice the last line to learn about what you need to do next
> (use "git commit" to conclude merge)

once you run that command, share `git status` output again

**Comment by ansary14-zz** [comment]
after run `git commit`
![Screenshot from 2020-09-03 21-02-49](https://user-images.githubusercontent.com/33208962/92132361-dfdb1180-ee28-11ea-97bc-29ecf1f2c42b.png)

**Comment by wasifhossain** [comment]
now enter a commit message and close the file

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/alpha-blog$ git status
> On branch master
> Your branch is ahead of 'origin/master' by 3 commits.
>   (use "git push" to publish your local commits)
> 
> nothing to commit, working tree clean
> ayub@ayub:~/alpha-blog$ git push
> Username for 'https://github.com': ansary14
> Password for 'https://ansary14@github.com': 
> Enumerating objects: 63, done.
> Counting objects: 100% (52/52), done.
> Delta compression using up to 12 threads
> Compressing objects: 100% (31/31), done.
> Writing objects: 100% (31/31), 5.43 KiB | 1.81 MiB/s, done.
> Total 31 (delta 11), reused 0 (delta 0)
> remote: Resolving deltas: 100% (11/11), completed with 11 local objects.
> remote: 
> remote: GitHub found 15 vulnerabilities on ansary14/alpha-blog's default branch (3 high, 9 moderate, 3 low). To find out more, visit:
> remote:      https://github.com/ansary14/alpha-blog/network/alerts
> remote: 
> To https://github.com/ansary14/alpha-blog.git
>    20f6963..1baf4b2  master -> master
