### ISSUE TITLE
setting up a new Ruby env

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#115]
Yesterday I was trying to setup ruby env(From here https://github.com/rbenv/rbenv#installation) in a new pc and while doing that the pc hanged badly... after several hours later it was same... so I have to force shut down that.
So now while trying to reinstall this error came up
```
faiyaz@faiyaz-Vostro-3460:~$ brew install rbenv
Updating Homebrew...
error: Not a valid ref: refs/remotes/origin/master
fatal: ambiguous argument 'refs/remotes/origin/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'


```
it is  hanging there means maybe I need to give some input...

**Comment by wasifhossain** [comment]
are you using **homebrew** command on Linux !!! its meant for MacOS only
