### ISSUE TITLE
category_id changes into categories_id after migration but why?

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#117]
In my `db/migrate/...create_article_categories.rb` 
I wrire it **5th line** **`t.integer :category_id`**
![Screenshot from 2020-09-16 19-07-53](https://user-images.githubusercontent.com/33208962/93341673-38aaa100-f850-11ea-9d9a-67cfdfb75da6.png)

After migration it shows in `db/schema.rb`
In **17th line** **`t.integer "categories_id"`**
But why?
![Screenshot from 2020-09-16 19-11-14](https://user-images.githubusercontent.com/33208962/93341862-70b1e400-f850-11ea-92ab-7e72a9d32746.png)

**Comment by wasifhossain** [comment]
could you share the contents of db/schema.rb as text

**Comment by ansary14-zz** [comment]
`db/schema.rb`
```
ActiveRecord::Schema.define(version: 2020_09_06_125246) do

  create_table "article_categories", force: :cascade do |t|
    t.integer "article_id"
    t.integer "categories_id"
  end

  create_table "articles", force: :cascade do |t|
    t.string "title"
    t.text "description"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer "user_id"
  end

  create_table "categories", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "username"
    t.string "email"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "password_digest"
    t.boolean "admin", default: false
  end

end

```

**Comment by ansary14-zz** [comment]
`db/migrate/..._create_article_categories.rb`
```
class CreateArticleCategories < ActiveRecord::Migration[6.0]
  def change
    create_table :article_categories do |t|
    	t.integer :article_id
    	t.integer :category_id
    end
  end
end
```

**Comment by wasifhossain** [comment]
and what about `app/models/article_category.rb`

**Comment by ansary14-zz** [comment]
`app/models/article_category.rb`

```
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end
```

**Comment by wasifhossain** [comment]
don't see any reason for the field to be named as `categories_id` in `arcticle_categories` table

could you delete the schema file and run `rails db:migrate`? it will regenerate the schema file. let us know if you still see the same result: field name in plural form

**Comment by ansary14-zz** [comment]
After deleting the schema file
Run `rails db:migrate`
The new schema file shows the same 
```

ActiveRecord::Schema.define(version: 2020_09_06_125246) do

  create_table "article_categories", force: :cascade do |t|
    t.integer "article_id"
    t.integer "categories_id"
  end
```

**Comment by wasifhossain** [comment]
in that case, the db already got the table `article_categories` created that way. 

you could apply a new migration to fix the name of the field

**Comment by ansary14-zz** [comment]
What do I do with the existing one?

**Comment by wasifhossain** [comment]
if you dont have more than a few thousands of records, you can use [`rename_column`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column)

for large volume of data, and if the app is used by real users, you have to go for more sophisticated way to avoid db downtime
- add a new column with intended name
- copy old column values to the new one
- delete the old column

**Comment by ansary14-zz** [comment]
https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-rename_column

Syntax error shows
```
ayub@ayub:~/alpha-blog$ rename_column(:article_categories, :categories_id, :category_id)
-bash: syntax error near unexpected token `:article_categories,'
```

**Comment by wasifhossain** [comment]
that is meant to be in a migration file, i.e. in ruby code; not in shell :stuck_out_tongue:

**Comment by ansary14-zz** [comment]
### It works!

First I generate a migration, `rails generate migration fix_column_name`

In the migration file, I added `rename_column(:article_categories, :categories_id, :category_id)`
Then run the migration `rails db:migrate`

It finally changes the **schema.rb** file.
