### ISSUE TITLE
Could'nt read from remote repository - connect to github using ssh

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#118]
```
ayub@ayub:~/rails-project/message-me$ git push -u origin master
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ansary14-zz** [comment]
My environments are
```
ayub@ayub:~/rails-project/message-me$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
ayub@ayub:~/rails-project/message-me$ rails -v
Rails 5.2.4.4

```

**Comment by ansary14-zz** [comment]
```
ayub@ayub:~/rails-project/message-me$ git remote add origin git@github.com:ansary14/message-me.git
fatal: remote origin already exists.

```

**Comment by wasifhossain** [comment]
most probably you need to connect your ssh account to github. could you check this:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/testing-your-ssh-connection

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ ssh -T git@github.com
Warning: Permanently added the RSA host key for IP address '192.30.255.113' to the list of known hosts.
git@github.com: Permission denied (publickey).

**Comment by ansary14-zz** [comment]
Checking existing ssh key
> ayub@ayub:~/rails-project/message-me$ ls -al ~/.ssh
total 12
drwx------  2 ayub ayub 4096 Oct 10 21:28 .
drwxr-xr-x 29 ayub ayub 4096 Oct 11 21:30 ..
-rw-r--r--  1 ayub ayub 2210 Oct 11 21:33 known_hosts

**Comment by wasifhossain** [comment]
> Checking existing ssh key
> 
> > ayub@ayub:~/rails-project/message-me$ ls -al ~/.ssh
> > total 12
> > drwx------  2 ayub ayub 4096 Oct 10 21:28 .
> > drwxr-xr-x 29 ayub ayub 4096 Oct 11 21:30 ..
> > -rw-r--r--  1 ayub ayub 2210 Oct 11 21:33 known_hosts

seems like your ssh directory is missing the key! most probably you have switched to different machine or reinstalled OS with fresh configuration.

in that case, setup a new ssh key as described in the link I shared above and try again

**Comment by ansary14** [comment]
Setup new ssh key

> ayub@ayub:~/rails-project/message-me$ ssh-keygen -t rsa -b 4096 -C "ayubuapcse@gmail.com"
Generating public/private rsa key pair.
Enter file in which to save the key (/home/ayub/.ssh/id_rsa): 
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in /home/ayub/.ssh/id_rsa
Your public key has been saved in /home/ayub/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:3K6T4nsyRR+JjcuKbO79MJgsjCXinvA0H1hJNCSezJY ayubuapcse@gmail.com
The key's randomart image is:
+---[RSA 4096]----+
|  ..+            |
| + = .           |
|  E .    + .     |
| . . . .+.+      |
|o . o  oSo..     |
|o= + o  +..      |
|o.*.=.oo ..      |
|oo.++o=o+.       |
| o.++.+Bo.       |
+----[SHA256]-----+

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ ls -al ~/.ssh
total 20
drwx------  2 ayub ayub 4096 Oct 11 21:48 .
drwxr-xr-x 29 ayub ayub 4096 Oct 11 21:30 ..
-rw-------  1 ayub ayub 3434 Oct 11 21:48 id_rsa
-rw-r--r--  1 ayub ayub  746 Oct 11 21:48 id_rsa.pub
-rw-r--r--  1 ayub ayub 2210 Oct 11 21:33 known_hosts

**Comment by ansary14-zz** [comment]
```
ayub@ayub:~/rails-project/message-me$ eval "$(ssh-agent -s)"
Agent pid 4619
```
```
ayub@ayub:~/rails-project/message-me$ ssh-add ~/.ssh/id_rsa
Enter passphrase for /home/ayub/.ssh/id_rsa: 
Identity added: /home/ayub/.ssh/id_rsa (ayubuapcse@gmail.com)
```
```
ayub@ayub:~/rails-project/message-me$ git remote -v
origin	git@github.com:ansary14/message-me.git (fetch)
origin	git@github.com:ansary14/message-me.git (push)
```

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ sudo apt-get install xclip
> [sudo] password for ayub:            
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following packages were automatically installed and are no longer required:
>   linux-headers-5.4.0-40 linux-headers-5.4.0-40-generic linux-headers-5.4.0-42
>   linux-headers-5.4.0-42-generic linux-headers-5.4.0-45
>   linux-headers-5.4.0-45-generic linux-image-5.4.0-40-generic
>   linux-image-5.4.0-42-generic linux-image-5.4.0-45-generic
>   linux-modules-5.4.0-40-generic linux-modules-5.4.0-42-generic
>   linux-modules-5.4.0-45-generic linux-modules-extra-5.4.0-40-generic
>   linux-modules-extra-5.4.0-42-generic linux-modules-extra-5.4.0-45-generic
>   nvidia-kernel-common-440 nvidia-kernel-source-440 nvidia-utils-440
>   xserver-xorg-video-nvidia-440
> Use 'sudo apt autoremove' to remove them.
> The following NEW packages will be installed:
>   xclip
> 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
> Need to get 18.4 kB of archives.
> After this operation, 60.4 kB of additional disk space will be used.
> Get:1 http://mirror.dhakacom.com/ubuntu-archive focal/universe amd64 xclip amd64 0.13-1 [18.4 kB]
> Fetched 18.4 kB in 0s (520 kB/s) 
> Selecting previously unselected package xclip.
> (Reading database ... 518814 files and directories currently installed.)
> Preparing to unpack .../xclip_0.13-1_amd64.deb ...
> Unpacking xclip (0.13-1) ...
> Setting up xclip (0.13-1) ...
> Processing triggers for man-db (2.9.1-1) ...
>

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ xclip -sel clip < ~/.ssh/id_rsa.pub

> ayub@ayub:~/rails-project/message-me$ ssh -T git@github.com
> Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
> git@github.com: Permission denied (publickey).

**Comment by wasifhossain** [comment]
did you add the ssh public key to your github settings (https://github.com/settings/keys)?

**Comment by ansary14-zz** [comment]
Which one is ssh public key

`SHA256:3K6T4nsyRR+JjcuKbO79MJgsjCXinvA0H1hJNCSezJY`
this one?

**Comment by wasifhossain** [comment]
> Which one is ssh public key

content of `~/.ssh/id_rsa.pub`

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ ~/.ssh/id_rsa.pub
-bash: /home/ayub/.ssh/id_rsa.pub: Permission denied

**Comment by wasifhossain** [comment]
you need to open the file in an editor, copy the content and paste it on github

**Comment by wasifhossain** [comment]
> > ayub@ayub:~/rails-project/message-me$ ~/.ssh/id_rsa.pub

by this, you are saying the shell to execute a program named `id_rsa.pub`; which is clearly not the case that you desire

**Comment by ansary14-zz** [comment]
My brain stuck ... my bad

**Comment by wasifhossain** [comment]
> you need to open the file in an editor, copy the content and paste it on github

didn't you get what I said here

**Comment by ansary14-zz** [comment]
Yes I got

**Comment by ansary14-zz** [comment]
Adding SSH key finally in github

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ ssh -T git@github.com
Hi ansary14! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by wasifhossain** [comment]
now you should be able to `git push ...` to github

**Comment by ansary14-zz** [comment]
Yes, I do. 
(Solved)
