### ISSUE TITLE
Is there any difference between form_for and form_with

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#120]
Is there any difference between `form_for` and `form_with`
In my previous application, for creating a **form** like a **login form**
I am using `<%= form_with(.............................) do |f|  %>` 
ruby version: **2.6.3**
But Now for the same purpose, creating a **login form**,
They used `<%= form_for(...............................) do |f|  %>` 
ruby version: **2.5.1**
Why form_for why not form_with?

**Comment by ansary14-zz** [comment]
But in my case, it shows an error
when I used `form_with` instead of  `form_for`
![Screenshot from 2020-10-24 10-25-45](https://user-images.githubusercontent.com/33208962/97067877-420ff180-15e4-11eb-92d9-920753a11353.png)


`form_for ` working perfectly.

**Comment by ansary14-zz** [comment]
Here is the error line
      `<%= form_with(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>`

**Comment by wasifhossain** [comment]
can you share the output of `rails routes | grep -i login`

**Comment by wasifhossain** [comment]
if you look closely at the api of these 2 helper methods:
- [form_with](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_with) (combines the functionality of both form_for + form_tag)
- [form_for](https://api.rubyonrails.org/classes/ActionView/Helpers/FormHelper.html#method-i-form_for)

the only change that you would have to make is use the `:scope` option to pass `:session` instead of passing it directly as you have done with `form_for`
```rb
form_with scope: :session, html: {class: "ui form", role: "form"}, url: login_path do |f|
```

**Comment by ansary14-zz** [comment]
But When I am using  **scope: :session** it runs  (no error message)
<%= form_with(scope: :session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>

**Comment by wasifhossain** [comment]
> But When I am using **scope: :session** it runs (no error message)
> <%= form_with(scope: :session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>

in that case, you should consider this as resolved :smile: , as this is how `form_with` should be used

**Comment by ansary14-zz** [comment]
But now I have a problem with `login_path`
![Screenshot from 2020-10-24 11-10-08](https://user-images.githubusercontent.com/33208962/97068461-9f5a7180-15e9-11eb-9312-a05bd3674afd.png)

**login** button didn't work

**Comment by wasifhossain** [comment]
if you had a model instance, e.g. `@post` or a local variable that holds some model instance, you would pass it using `:model` option to `form_with` like:
```rb
form_with model: @post do |f|
```

**Comment by wasifhossain** [comment]
could you send the server log that contains any relevant error msg as well as dev console error msg inside your browser in case there is any JS error

you might share the server log that is generated upon clicking the `Login` button

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/rails-project/message-me$ rails s
> => Booting Puma
> => Rails 5.2.4.4 application starting in development 
> => Run `rails server -h` for more startup options
> Puma starting in single mode...
> * Version 3.12.6 (ruby 2.5.1-p57), codename: Llamas in Pajamas
> * Min threads: 5, max threads: 5
> * Environment: development
> * Listening on tcp://localhost:3000
> Use Ctrl-C to stop
> Started POST "/login" for 127.0.0.1 at 2020-10-24 11:18:50 +0600
>    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
>   ↳ /home/ayub/.rvm/gems/ruby-2.5.1/gems/activerecord-5.2.4.4/lib/active_record/log_subscriber.rb:98
>   
> ActionController::RoutingError (No route matches [POST] "/login"):
>   
> actionpack (5.2.4.4) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
> web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
> web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
> web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
> web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
> actionpack (5.2.4.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
> railties (5.2.4.4) lib/rails/rack/logger.rb:38:in `call_app'
> railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `block in call'
> activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `block in tagged'
> activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:28:in `tagged'
> activesupport (5.2.4.4) lib/active_support/tagged_logging.rb:71:in `tagged'
> railties (5.2.4.4) lib/rails/rack/logger.rb:26:in `call'
> sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
> actionpack (5.2.4.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
> actionpack (5.2.4.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
> rack (2.2.3) lib/rack/method_override.rb:24:in `call'
> rack (2.2.3) lib/rack/runtime.rb:22:in `call'
> activesupport (5.2.4.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
> actionpack (5.2.4.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
> actionpack (5.2.4.4) lib/action_dispatch/middleware/static.rb:127:in `call'
> rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
> railties (5.2.4.4) lib/rails/engine.rb:524:in `call'
> puma (3.12.6) lib/puma/configuration.rb:227:in `call'
> puma (3.12.6) lib/puma/server.rb:706:in `handle_request'
> puma (3.12.6) lib/puma/server.rb:476:in `process_client'
> puma (3.12.6) lib/puma/server.rb:334:in `block in run'
> puma (3.12.6) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
>

**Comment by wasifhossain** [comment]
output of `rails routes | grep -i login` pls

**Comment by ansary14-zz** [comment]
I expect it will show me like that

![Screenshot from 2020-10-24 11-22-59](https://user-images.githubusercontent.com/33208962/97068646-55728b00-15eb-11eb-97db-e2a3fbcfa66a.png)


It return when I was used `<%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>`

**Comment by ansary14-zz** [comment]
the output of `rails routes | grep -i login`
```
ayub@ayub:~/rails-project/message-me$ rails routes | grep -i login
                    login GET  /login(.:format)                                                                         sessions#new

```

**Comment by wasifhossain** [comment]
alright. the concept is that when you submit a form, it can be any of a POST | PUT | PATCH request, but not a GET request. but your routes file defined the /login route as GET. thats why the submission failed.

to fix it, you have to define the route as POST, as the form expected

**Comment by ansary14-zz** [comment]
#reopen

**Comment by ansary14-zz** [comment]
I am trying many thing, But `form_with` didn't work

like
I added in my `routes.rb`
`  post 'login', to: 'sessions#create'  `
Then I added **create** method 
under` controller/sessions_controller.rb`

**Comment by ansary14-zz** [comment]
And I changed this
`<%= form_with(scope: :session, class: "ui form", role: "form", url: login_path) do |f| %>`

Previously,
`<%= form_with(scope: :session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>`

**Comment by wasifhossain** [comment]
> And I changed this
> `<%= form_with(scope: :session, class: "ui form", role: "form", url: login_path) do |f| %>`

html attributes need to be wrapped inside the `:html` option. so the previous one is correct

**Comment by ansary14-zz** [comment]
Ok. i changed it like the previous one

**Comment by wasifhossain** [comment]
whats the latest error msg that you are getting

**Comment by ansary14-zz** [comment]
[https://m.patrikonrails.com/rails-5-1s-form-with-vs-old-form-helpers-3a5f72a8c78a](url)

![Screenshot from 2020-10-24 20-12-52](https://user-images.githubusercontent.com/33208962/97083933-5b8d5980-1635-11eb-93d9-f02967009b7c.png)

**Comment by wasifhossain** [comment]
ok good. you can check out the options from the api reference that you could pass in `form_with` helper.

**Comment by ansary14-zz** [comment]
**1st Question**

`<%= form_with(scope: :session, class: "ui form", role: "form", url: login_path) do |f| %>`

`<%= form_with(scope: :session, html: { class: "ui form", role: "form" }, url: login_path) do |f| %>`

` <%= form_for(:session, html: { class: "ui form", role: "form" }, url: login_path) do |f| %>`

All are work perfectly.
But why?
Why not difference?

**Comment by ansary14-zz** [comment]
**2nd Question**

`<%= f.submit "login", class: "ui orange submit button" %>`

`<%= f.button "login", class: "ui orange submit button" %>`

Both are the same but Why?

**Comment by wasifhossain** [comment]
> **1st Question**
> 
> `<%= form_with(scope: :session, class: "ui form", role: "form", url: login_path) do |f| %>`
> 
> `<%= form_with(scope: :session, html: { class: "ui form", role: "form" }, url: login_path) do |f| %>`
> 
> ` <%= form_for(:session, html: { class: "ui form", role: "form" }, url: login_path) do |f| %>`
> 
> All are work perfectly.
> But why?
> Why not difference?

all versions that you mentioned above are correct :heavy_check_mark: 

after all, `form_with` is meant to serve all functionalities that you get from `form_for` and `form_tag`, but in elegant way. Why do you expect them to act different ?!

**Comment by wasifhossain** [comment]
> **2nd Question**
> 
> `<%= f.submit "login", class: "ui orange submit button" %>`
> 
> `<%= f.button "login", class: "ui orange submit button" %>`
> 
> Both are the same but Why?

visual output might be the same, but if you check the DOM inside browser developer console generated by these 2 helpers, you would find that
- `f.submit` generates an `input` element of type `submit`
- `f.button` generates a `button` element of type `submit`

so there's subtle difference between the two. I would prefer to use `f.submit` to have `<input type="submit">` DOM output

**Comment by ansary14-zz** [comment]
Thanks for clear my confusion.
