### ISSUE TITLE
Error flash message not shown up!

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#121]
`flash[:success] = "You have successfully logged in"`
`flash[:success] = "You have successfully logged out"`
success message render properly.

![Screenshot from 2020-10-26 10-20-20](https://user-images.githubusercontent.com/33208962/97133727-2556f380-1775-11eb-91e8-2b11729222e1.png)

![Screenshot from 2020-10-26 10-22-44](https://user-images.githubusercontent.com/33208962/97133754-3acc1d80-1775-11eb-8bff-9618c8a9d64c.png)

**Comment by ansary14-zz** [comment]
When I am passing **wrong information** in the **login** section
No **error message** is shown there

`flash.now[:error] = "There was something wrong with your login details"`

**Comment by ansary14-zz** [comment]
Here is my `layouts/application.html.erb` file
```
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>

    </div>
  </body>
</html>

```

**Comment by ansary14-zz** [comment]
Here is my `layouts/_messages.html.erb` file

```
<% flash.each do|message_type, message_content| %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message_content %>
    </div>
  </div>
<% end %>
```

**Comment by ansary14-zz** [comment]
reference code
https://semantic-ui.com/collections/message.html

![Screenshot from 2020-10-26 10-34-40](https://user-images.githubusercontent.com/33208962/97134248-eaee5600-1776-11eb-88f7-c4870e7d0880.png)

**Comment by ansary14-zz** [comment]
Here `app/assets/javascripts/application.js` file
```

$(document).on('turbolinks:load', function() {
  $('.ui.dropdown').dropdown();
  $('.message .close').on('click', function() {
    $(this).closest('.message').transition('fade');
  });
})

```

**Comment by ansary14-zz** [comment]
Here `controllers/sessions_controller.rb` file

```
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have successfully logged out"
    redirect_to login_path
  end

end

```

**Comment by ansary14-zz** [comment]
When I am using `form_for` instead of `form_with`
`<%= form_for(:session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>`

It shows an error message perfectly
![Screenshot from 2020-10-26 18-30-06](https://user-images.githubusercontent.com/33208962/97172676-8f918780-17b9-11eb-84df-623f6008fe04.png)

**Comment by ansary14-zz** [comment]
`<%= form_with(scope: :session, html: {class: "ui form", role: "form"}, url: login_path) do |f| %>`
`<%= form_with(scope: :session, class: "ui form", role: "form", url: login_path) do |f| %>`

Both are not showing the **_error_** message only show the **success** message!
But why?

**Comment by wasifhossain** [comment]
- `flash` can hold messages to display in the **next** action
- `flash.now` holds messages to display in the **current** action

i see that you are only using `flash` to iterate over the success messages in `layouts/_messages.html.erb`. you also need to incorporate `flash.now` to show the error messages

flash api: https://api.rubyonrails.org/classes/ActionDispatch/Flash/FlashHash.html

**Comment by wasifhossain** [comment]
btw, are you submitting your form using unobtrusive XHR? if not, then make sure you provide `local: true` option while using `form_with`

so your code might look like this:
```rb
<%= form_with url: login_path, scope: :session, local: true, class: 'ui form', html: { role: 'form' } do |f| %>
```

**Comment by ansary14-zz** [comment]
It's working.

**Comment by wasifhossain** [comment]
> What is unobtrusive XHR ?

in case of `form_with`, which uses unobtrusive XHR by default, that means if the user's browser is allowed to run javascript, i.e. if JS is not disabled, then the form data will be submitted to the server using XHR (with the help of JS). No page refresh takes place in this way.

and if JS is disabled in case, the form submission will still work (thats the point of "unobtrusiveness"), but in traditional way (page refresh happens)

by providing `local: true` option, you are basically forcing the form to always submit form data to the server in **traditional** way.

for more details on what does it mean by "obtrusive" XHR, please check https://blog.teamtreehouse.com/unobtrusive-javascript-important

this stackoverflow qn might also help to get the idea from different perspective: https://stackoverflow.com/questions/7788956/submit-form-without-javascript/7789000
