### ISSUE TITLE
I expect localhost:3000 says ... pop up on my index template but don't

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#122]
I expect localhost:3000 says.. pop up on my index template like below
![Screenshot from 2020-10-27 18-40-32](https://user-images.githubusercontent.com/33208962/97303621-d5675200-1884-11eb-8db8-6028c36b9eb3.png)

**Comment by ansary14-zz** [comment]
But I don't see any like this

**Comment by ansary14-zz** [comment]
At first, I am generating a channel name chatroom
Here is `app/channel/chatroom_channel.rb` file

```
class ChatroomChannel < ApplicationCable::Channel
  def subscribed
    stream_from "chatroom_channel"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end
end
```

**Comment by ansary14-zz** [comment]
Here is `routes.rb` file

```
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end
```

**Comment by ansary14-zz** [comment]
Here is `messages_controller.rb`


```
  class MessagesController < ApplicationController
  before_action :require_user

  def create
      message = current_user.messages.build(message_params)
      if message.save
        ActionCable.server.broadcast "chatroom_channel", foo: message.body
      end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end
end

```

**Comment by ansary14-zz** [comment]
Here is `javascripts/channel/chatroom.coffee` file
```

App.chatroom = App.cable.subscriptions.create "ChatroomChannel",
  connected: ->
    # Called when the subscription is ready for use on the server

  disconnected: ->
    # Called when the subscription has been terminated by the server

  received: (data) ->
    alert data.foo
```

**Comment by ansary14-zz** [comment]
https://guides.rubyonrails.org/action_cable_overview.html#client-side-components-connections

Here They say, This can be established using the following JavaScript, which is generated by default by Rails

> I think it only for **rails 6**

Because in **rails 5** When I create a channel by **rails generator**
`rails generate channel chatroom`
Its create 2 files here a picture of that
```

ayub@ayub:~/rails-project/message-me$ rails generate channel chatroom
Running via Spring preloader in process 6253
      create  app/channels/chatroom_channel.rb
   identical  app/assets/javascripts/cable.js
      create  app/assets/javascripts/channels/chatroom.coffee

```
**rails generator didn't create** something like below they mentioned earlier
`app/javascript/channels/consumer.js`

**Comment by wasifhossain** [comment]
makes sense if you are not using rails 6.

did you know that you could provide the rails version in the doc link? e.g. if you are using rails 5.2.4.4, then you should read the guide here: https://guides.rubyonrails.org/v5.2.4.4/action_cable_overview.html#client-side-components-connections

note: without any version in the link, the site assumes that you are looking for the **latest stable version** of rails guide

**Comment by ansary14-zz** [comment]
I think I'm solved my issues.
```
        <%= form_with model: @messages, url: message_path, local: true, class: "ui reply form", html: { role: "form" } do |f| %>
```
I just remove the local: true from the above line in `app/views/chatroom/index.html.erb`
and it works !
Now the line is 
```

<%= form_with model: @messages, url: message_path, class: "ui reply form", html: { role: "form" } do |f| %>

```

And it pop up my expectation
![Screenshot from 2020-10-31 23-13-17](https://user-images.githubusercontent.com/33208962/97785352-b80ced80-1bce-11eb-916d-a0ce2a79a64d.png)

 in my index template

**Comment by wasifhossain** [comment]
it should give you great feeling when you can solve some problem on your own :raised_hands:

**Comment by ansary14-zz** [comment]
Yes, vaia.

**Comment by youshamahmood96** [comment]
@wasifhossain  bhaiya this issue and solution to this issue made me think that whether the javascript alert feature refreshes a page on pop up?
just curious.

**Comment by wasifhossain** [comment]
@youshamahmood96 actually no.
