### ISSUE TITLE
RVM USE error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#123]
In my ubuntu 18.04 LTS ,Ruby 2.5.1 was installed, but I have some previous ROR projects on 2.6.5.. so I installed ruby 2.6.5 but idk why this error is throwing
```
abir@abir:~$ rvm --default use ruby-2.6.5
RVM is not a function, selecting rubies with 'rvm use ...' will not work.
You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.
abir@abir:~$ 
```
I checked https://rvm.io/integration/gnome-terminal/ and enabled the `run command as a login shell`

**Comment by wasifhossain** [comment]
since you have enabled the login shell, did you try the command inside a new shell? if not, give it a try and come back with any new error msg

**Comment by sadmanahmed** [comment]
Solved by opening in a new shell 
```
abir@abir:~/Ruby code/instagramm$ rvm --default use ruby-2.6.5
Using /home/abir/.rvm/gems/ruby-2.6.5
abir@abir:~/Ruby code/instagramm$ 
abir@abir:~/Ruby code/instagramm$ ruby -v
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]

```
