### ISSUE TITLE
Postgresql setup

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#125]
**FOllow this for create role directly : https://kb.objectrocket.com/postgresql/how-to-create-a-role-in-postgres-1454**

I was actually followed this for postgresql setup but it gives an error
![Screenshot from 2020-10-29 02-55-20](https://user-images.githubusercontent.com/19534210/97496257-e7371b00-1992-11eb-9043-7de4f553b9e2.png)

**Comment by sadmanahmed** [comment]
what would be the password as I tried with the main password and it return failure
```
abir@abir:~/Ruby code/instagramm$ su - postgres
Password: 
su: Authentication failure

```

**Comment by sadmanahmed** [comment]
already saw #75 , #96 and #98 but didnot find the answer needed

**Comment by sadmanahmed** [comment]
this is solved right now 
```
abir@abir:~/Ruby code/instagramm$ sudo -u postgres psql
[sudo] password for abir: 
psql (10.14 (Ubuntu 10.14-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# ALTER USER postgres PASSWORD 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
ALTER ROLE
postgres=# \q
abir@abir:~/Ruby code/instagramm$ su - postgres
Password: 
su: Authentication failure
abir@abir:~/Ruby code/instagramm$ sudo passwd postgres
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully
abir@abir:~/Ruby code/instagramm$ su - postgres
Password: 
postgres@abir:~$ 

```

**Comment by sadmanahmed** [comment]
My .env file and this output is same
```
abir@abir:~/Ruby code/instagramm$ echo $PG_USERNAME

abir@abir:~/Ruby code/instagramm$ rails c
Running via Spring preloader in process 5220
Loading development environment (Rails 6.0.3.2)
2.6.5 :001 > ENV['PG_USERNAME'] 
 => "abir" 
2.6.5 :002 > ENV['PG_PASSWORD'] 
 => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 
2.6.5 :003 > ^C
2.6.5 :003 > 

```
I have followed all the steps properly but I dont know why this error is throwing again and again
```
rails db:environment:set
rails aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "abir"
FATAL:  password authentication failed for user "abir"
.
.
.
.
.

```

```
 rails db:create
FATAL:  password authentication failed for user "abir"
FATAL:  password authentication failed for user "abir"
Couldn't create 'instagramm_development' database. Please check your configuration.
rails aborted!
PG::ConnectionBad: FATAL:  password authentication failed for user "abir"
FATAL:  password authentication failed for user "abir"

.
.
.
.
.

```

**All my postgres password is same**

**Comment by wasifhossain** [comment]
**the idea is that you have to configure the password for the user that you set in `ENV['PG_USERNAME']`**

the following configures this for **user "postgres"**
> abir@abir:~/Ruby code/instagramm$ sudo -u postgres psql
> [sudo] password for abir: 
> psql (10.14 (Ubuntu 10.14-0ubuntu0.18.04.1))
> Type "help" for help.
> 
> postgres=# ALTER USER postgres PASSWORD 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';
> ALTER ROLE
> postgres=# \q
> abir@abir:~/Ruby code/instagramm$ su - postgres
> Password: 
> su: Authentication failure
> abir@abir:~/Ruby code/instagramm$ sudo passwd postgres
> Enter new UNIX password: 
> Retype new UNIX password: 
> passwd: password updated successfully
> abir@abir:~/Ruby code/instagramm$ su - postgres
> Password: 
> postgres@abir:~$

just do the same for **user "abir"**

**Comment by sadmanahmed** [comment]
```
postgres=# su -abir
postgres-# psql
postgres-# \password abir
Enter new password: 
Enter it again: 
ERROR:  role "abir" does not exist
postgres-# \du
postgres-# 

```
so I think I have to create roll 'abir'.
going to implement this
```

CREATE ROLE abir WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD 'abir1234';
--



```

**Comment by sadmanahmed** [comment]
Followed this link to create roll https://kb.objectrocket.com/postgresql/how-to-create-a-role-in-postgres-1454

![Screenshot from 2020-10-30 19-41-53](https://user-images.githubusercontent.com/19534210/97712876-3e4f0400-1ae9-11eb-8d9c-bd6369f82ba6.png)

**Comment by sadmanahmed** [comment]
```
postgres@abir:~$ su abir
Password: 
su: Authentication failure
postgres@abir:~$ su abir
Password: 
abir@abir:/var/lib/postgresql$ sudo passwd abir
Enter new UNIX password: 
Retype new UNIX password: 
passwd: password updated successfully

```

**Comment by sadmanahmed** [comment]
```
abir@abir:~/Ruby code/instagramm$ rvm use 2.6.5
Using /home/abir/.rvm/gems/ruby-2.6.5
abir@abir:~/Ruby code/instagramm$ bundle install
.
.
.
.
abir@abir:~/Ruby code/instagramm$ rails db:create
Created database 'instagramm_development'
Created database 'instagramm_test'
abir@abir:~/Ruby code/instagramm$ rails db:migrate
== 20200815191151 CreatePics: migrating =======================================
.
.
.
```
Alhamdulillah

**Comment by wasifhossain** [comment]
well done :+1:
