### ISSUE TITLE
What is the difference between bundle install and bundle install --without production ?

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#128]
If I run `bundle install` instead of `bundle install --without production`  Have any problem?

**Comment by wasifhossain** [comment]
NO. 

- `bundle install`: will download AND install all gems found across all groups mentioned in Gemfile
- `bundle install --without production`: will do the same for all groups mentioned in Gemfile, **except `production` group**

For details: https://bundler.io/v2.1/man/bundle-install.1.html#INSTALLING-GROUPS
