### ISSUE TITLE
send activation email other than part of signup process

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#13]

**Comment by wasifhossain** [comment]
are you talking about sending an activation email to a registered user during login?

**Comment by sadmanahmed** [comment]
Yes, like I have been register with abirssc@gmail.com already before adding this feature. Now when I am trying to login ,a flash message is showing to activate my email at first.

**Comment by wasifhossain** [comment]
should be simple.

you may add a link on the login page saying "**Didn't receive confirmation instructions?**", clicking on which will take the user to a new form, e.g. `confirmations#new` action.

this form will take the user email as input and once submitted, another action (e.g. `confirmations#create`) will check if there is a user available with the input email and if its not confirmed yet. In such case, it would call the same user method that sends activation email (used in the signup process)

**Comment by sadmanahmed** [comment]
Let me check
