### ISSUE TITLE
BLOG issue

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#130]
![image](https://user-images.githubusercontent.com/19534210/98591835-04f17200-22fb-11eb-9e20-d4d276d9bec6.png)

After pressing the save button this appears ,but it should render to the root ,right?

Server log
```
Started POST "/posts" for ::1 at 2020-11-10 02:16:25 +0600
Processing by PostsController#create as HTML
  Parameters: {"authenticity_token"=>"AwrfwQA1aAVTFVs2lt8p+euVm5feQ4+7Iln35Q2xplIQUBk52j2mL6vJK9+Z6PSmmSkWfw2Pdjwhqw8Wa1+yug==", "post"=>{"title"=>"Hello", "body"=>"ssss"}, "commit"=>"Save"}
Redirected to http://localhost:3000posts_path
Completed 302 Found in 1ms (ActiveRecord: 0.0ms | Allocations: 397)
```

**Comment by sadmanahmed** [comment]
```
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end

  def create
    redirect_to 'posts_path'
  end
end

```

```
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts


end

```

**Comment by wasifhossain** [comment]
> Server log
> 
> ```
> Started POST "/posts" for ::1 at 2020-11-10 02:16:25 +0600
> Processing by PostsController#create as HTML
>   Parameters: {"authenticity_token"=>"AwrfwQA1aAVTFVs2lt8p+euVm5feQ4+7Iln35Q2xplIQUBk52j2mL6vJK9+Z6PSmmSkWfw2Pdjwhqw8Wa1+yug==", "post"=>{"title"=>"Hello", "body"=>"ssss"}, "commit"=>"Save"}
> Redirected to http://localhost:3000posts_path
> Completed 302 Found in 1ms (ActiveRecord: 0.0ms | Allocations: 397)
> ```

"Redirected to http://localhost:3000posts_path" <----- the path does NOT look okay!

caused from posts#create action: `redirect_to 'posts_path'`

as `posts_path` is a helper method generated from routes config that gets translated to a path, like /some/path, you have to invoke it as a method.

just remove the quotes around `posts_path` and it should work

**Comment by sadmanahmed** [comment]
Solved... I put **posts_path** in ' '
