### ISSUE TITLE
PDF validation

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#133]
This is the validation for the shrine gem(https://shrinerb.com/docs/validation) , read this whole but confused how to attach a pdf file here as i tried to add pdf in this file but throws error 
![image](https://user-images.githubusercontent.com/19534210/98875463-7f122a00-24a6-11eb-968a-000fd5d6335d.png)

```
class ImageUploader < Shrine
  Attacher.validate do
    validate_size      1..5*1024*1024
    validate_mime_type %w[image/jpeg image/png image/webp image/tiff image/pdf]
    validate_extension %w[jpg jpeg png webp tiff tif pdf]
  end
end

```

**Comment by wasifhossain** [comment]
you have to specify correct **mime types** for the files that your app should accept.

here is the list of common mime types. check it out yourself if you are doing it right!

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

**Comment by sadmanahmed** [comment]
okay it is posted now but how can I make it visible on the index.html.erb's html tag?
```
.
.
<p><%= image_tag post.image.url %></p>
.
.
```
should I use type like this `<embed src="study/sample.pdf" type="application/pdf"   height="300px" width="100%">` 

![image](https://user-images.githubusercontent.com/19534210/98934789-cc28e700-250c-11eb-998f-5cd5ee794589.png)

**Comment by wasifhossain** [comment]
you may render the link behind a text, e.g. 
```
<a href="url">filename.pdf</a>

**Comment by sadmanahmed** [comment]
How can I distinguish(it can be a if else case I guess) the system to catch the extension? e.g. : when I upload picture it will show the picture straight and when I will upload a pdf it will show a button `PDF` like here. 
** I can see both the picture and pdf  in the `PDF` button... 
```
<p><%= image_tag post.image.url %></p>
  <p><%= link_to "PDF", post.image.url %></p>
```
![image](https://user-images.githubusercontent.com/19534210/99112362-bc49f980-2617-11eb-86a3-7cab4a2a8406.png)

**Comment by wasifhossain** [comment]
you have to check the metadata of the attachment and figure out which mime type it has. based on that, you have to write the logic to label the button

this section on Shrine doc would help you learn how you can extract the metadata: https://shrinerb.com/docs/getting-started#metadata
