### ISSUE TITLE
Heroku error : The page you were looking for doesn't exist.

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#135]
![Screenshot from 2020-11-25 20-40-47](https://user-images.githubusercontent.com/33208962/100242048-8fbea780-2f5e-11eb-9d60-6b668376ff52.png)

When I click the remove button
it shows error like

![Screenshot from 2020-11-25 20-40-27](https://user-images.githubusercontent.com/33208962/100242161-ad8c0c80-2f5e-11eb-9a44-53e748c27bbf.png)

**Comment by ansary14-zz** [comment]
Here is the heroku build log 
[finance-tracker-ayub-logs-1606315360354.txt](https://github.com/ormprog/rails_ama/files/5597352/finance-tracker-ayub-logs-1606315360354.txt)

**Comment by wasifhossain** [comment]
> ActionController::RoutingError (No route matches [DELETE] "/user_stocks.1")

lets see the code that rendered the "Remove" button(s)

**Comment by ansary14-zz** [comment]
render **remove** button code
`<td><%= link_to 'Remove', user_stocks_path(stock), method: :delete, data: {confirm: 'Are you sure?'},
                              class: "btn btn-sm btn-warning" %></td>`

**Comment by ansary14-zz** [comment]
**destroy** action code
```
  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    user_stock.destroy
    flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio"
    redirect_to my_portfolio_path 
  end
```

**Comment by wasifhossain** [comment]
><td><%= link_to 'Remove', user_stocks_path(stock), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-warning" %></td>

it should be singular `user_stock_path(stock)`; not `stock**s**`

**Comment by ansary14-zz** [comment]
Okay But I confused with this

> ayub@ayub:~/rails-project/finance-tracker$ rails routes --expanded | grep user_stocks
> Prefix            | user_stocks
> URI               | /user_stocks(.:format)
> Controller#Action | user_stocks#create
> URI               | /user_stocks/:id(.:format)
> Controller#Action | user_stocks#destroy
>

**Comment by wasifhossain** [comment]
you get the helper method info from `rails routes`

run: `rails routes | grep -i user_stock` and share the output. you should see `user_stock` under the **Prefix** column for
```
user_stock   DELETE    /user_stocks/:id(.:format)
```

**Comment by wasifhossain** [comment]
> ayub@ayub:~/rails-project/finance-tracker$ rails routes --expanded | grep user_stocks

use singular `user_stock` after the `grep` command

**Comment by ansary14-zz** [comment]
Okay
