### ISSUE TITLE
localhost show full name perfecly But Heroku didn't

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#136]
Local host shows full name perfectly. After editing the profile.

![Screenshot from 2020-11-27 01-42-35](https://user-images.githubusercontent.com/33208962/100387348-12745f00-3052-11eb-93ff-98f828a87716.png)

But Heroku didn't show, its show Anonymous which was for such case where a first name or last name doesn't set by the user.

![Screenshot from 2020-11-27 01-46-56](https://user-images.githubusercontent.com/33208962/100387503-7434c900-3052-11eb-8083-ee26fa202a45.png)

**Comment by ansary14-zz** [comment]
Here is Heroku log file
[finance-tracker-ayub-logs-1606417452520.txt](https://github.com/ormprog/rails_ama/files/5604760/finance-tracker-ayub-logs-1606417452520.txt)

**Comment by wasifhossain** [comment]
could you share the code that renders the name

**Comment by ansary14-zz** [comment]
`<li class="nav-item user-name">
            <%= fa_icon 'user' %> <%= current_user.full_name %>
          </li>`

**Comment by ansary14-zz** [comment]
```
  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end
```

**Comment by ansary14-zz** [comment]
this application created with help by devise gem

**Comment by wasifhossain** [comment]
could you share the first_name and last_name of the user from rails console on Heroku, 

e.g. `User.find(:id).first_name` and `User.find(:id).last_name`

**Comment by ansary14-zz** [comment]
In Heroku rails console
both are **nil**.
All the users first_name and the last_name are nil

**Comment by wasifhossain** [comment]
> def full_name
>     return "#{first_name} #{last_name}" if first_name || last_name
>     "Anonymous"
>   end

thats the reason why full_name returned Anonymous

**Comment by wasifhossain** [comment]
according to the logic, `"#{first_name} #{last_name}"` will be returned only when at least one of first_name or last_name are non-nil values.

that also implies if at least of them are empty string, still `"#{first_name} #{last_name}"` will be used

**Comment by wasifhossain** [comment]
could you clarify when you would like to see `"#{first_name} #{last_name}"` and when Anonymous?

**Comment by ansary14-zz** [comment]
When I send you a peek video. This time I update profile (Edit profile)
with first name And last name
But after the update button press, it shows the message that updated successfully but the full name doesn't show.

**Comment by ansary14-zz** [comment]
But now when I repeat the process again in Heroku
Then it returns the full name. 
I didn't change anything....!

**Comment by wasifhossain** [comment]
so its now working, you think?

**Comment by ansary14-zz** [comment]
> could you clarify when you would like to see `"#{first_name} #{last_name}"` and when Anonymous?

When the user has a first name or last name then it shows the full name (first name or last name or both)
If both missing then Anynomous

**Comment by ansary14-zz** [comment]
> so its now working, you think?

Yes It's now working

**Comment by ansary14-zz** [comment]
I think I need some **patient** after **Heroku push**

**Comment by wasifhossain** [comment]
> > could you clarify when you would like to see `"#{first_name} #{last_name}"` and when Anonymous?
> 
> When the user has a first name or last name then it shows the full name (first name or last name or both)
> If both missing then Anynomous

ok its clear. nevertheless, you should care about the **empty string** too. 

when you submit the form with empty values, empty strings `''` are inserted  in place of `nil` in the corresponding fields. 

the following logic will match nil values but fail on empty strings
```rb
if first_name || last_name
```

if you want to match either nil or empty strings, you have to write it as
```rb
if first_name.present? || last_name.present?
```

**Comment by wasifhossain** [comment]
I would have written the logic as
```rb
def full_name
  name = [first_name.presence, last_name.presence].compact.join(' ').presence

  name || 'Anonymous'
end
```

cc @ansary14
