### ISSUE TITLE
How do I run migration on an already existing column without harming my database records.

### ISSUE THREAD

**Issue by youshamahmood96** [ormprog/rails_ama#137]
I have a table "A" in my database.
I did rails g migration add_password
it got added, no problem.
I edited the add_password and it worked fine.
I did rails db:migrate
Then I messed up with my gh branches and pushed a previous commit which did not include the add_password migration file
I continued working on the project , made a lot of changes.
It didnt cause any problem in my local as the table was already updated.
But when I pushed it to heroku, as there is no migration file for the add_password column, it didnt get added to the postgresql db in heroku and the app was crashing.
My fix:
I did rails g migration add_password again
I pushed it to heroku
I ran rails db:migrate
works fine.

My question:

**Can I do something like removing the column from my local db and then adding it again through migration without losing any record?**

**Comment by wasifhossain** [comment]
let me explain why do we really need activerecord migrations altogether.

in the past, companies tend to design the whole system before even writing a single line of code, which lead them to develop a strategy called **watefall model**.

in modern days, application requirements are so versatile that you can't even predict if the design that you make before writing any lines of code would last for a few months before you bring wholesale change to the initial design.

so software practitioners developed a strategy called **agile method**, where you will bootstrap a project with some initial design mockups and start writing code as early as it "makes sense". For that, you will use tools along the way that **would allow you to make changes to the design as easy as possible**.

**ActiveRecord Migration provided by Rails is that exact tool to help you achieve the goal.**

In the next post, I will try to address your question in a precise way. Stay tuned!

**Comment by wasifhossain** [comment]
could you share the output of the following command from both your local environment as well as heroku
```
rails db:migrate:status
```

on heroku, you could do it in one of the ways:
- run `heroku run rails db:migrate:status -a <heroku-app-name>`, or
- run `heroku run bash -a <heroku-app-name>` and next run the initial command

**Comment by youshamahmood96** [comment]
Local:

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20201126143506  ********** NO FILE **********
   up     20201126144354  Create articles1
   up     20201126144911  Add timestamps to articles
   up     20201129001751  Create users
   up     20201129010520  Add user id to articles
   up     20201129223258  ********** NO FILE **********
   up     20201130055004  Add admin to users

**Comment by youshamahmood96** [comment]
Heroku:
 up     20201126144354  Create articles1
   up     20201126144911  Add timestamps to articles
   up     20201129001751  Create users
   up     20201129010520  Add user id to articles
   up     20201130055004  Add admin to users
   up     20201130073521  Add password

**Comment by youshamahmood96** [comment]
My guess:
********** NO FILE ********** is cause because I tried to run migrate using a duplicate column name

**Comment by wasifhossain** [comment]
> My guess:
> ********** NO FILE ********** is cause because I tried to run migrate using a duplicate column name

it happens when you remove a migration file after applying it

**Comment by wasifhossain** [comment]
>Can I do something like removing the column from my local db and then adding it again through migration without losing any record?

short answer is: you can remove a column anytime, but that will cost you all the values in that column.

so i am thinking how you could manage to achieve your desired db schema in both local and remote (heroku) environments WITHOUT losing any values

**Comment by youshamahmood96** [comment]
YES
Thats exactly what I was thinking.
My solution is a manual one, it is not a good practise

**Comment by wasifhossain** [comment]
do you think any of your envs (either local/remote) have the desired db schema?

**Comment by youshamahmood96** [comment]
both my local and remote has desired db schema
they work fine

**Comment by wasifhossain** [comment]
then why do you need to remove a column

**Comment by youshamahmood96** [comment]
because.
My local app has a column which was generated by a single migration file
after generation, the schema got updated but the migration file got lost somehow
so when I push this to remote and then run rails db:migrate, this column doesnt get added to my db
I was thinking if I could remove the column locally and then run migration fresh

**Comment by youshamahmood96** [comment]
both in local and remote

**Comment by wasifhossain** [comment]
then i think
>My fix:
I did rails g migration add_password again
I pushed it to heroku
I ran rails db:migrate
works fine.

is the way to go to recover from the situation you found :smile: 

it might not look clean, but should work, as you have also confirmed that right now you have the desired db schema in both of your envs

**Comment by wasifhossain** [comment]
nevertheless, the best practice is:
> **NEVER REMOVE A MIGRATION ONCE YOU PUSH IT TO REMOTE (Heroku)**

if you feel that you have to make any modification to the schema once you push to remote, the best practice to do this is by writing a **new migration**

**Comment by youshamahmood96** [comment]
okay.
got it.
I think the manual solution was required as the mistake was manual.

**Comment by youshamahmood96** [comment]
should i close this issue?

**Comment by wasifhossain** [comment]
so the idea is, you will always **add migration files** along the whole lifecycle of your project and NEVER REMOVE ANY SINGLE OF THEM

that way the ordered migration files resided inside `db/migrate/` will give you the idea how the app evolved to the current state

**Comment by wasifhossain** [comment]
before closing the issue, i would like you to fix the local schema output that should NO LONGER show you
>  ********** NO FILE **********

**Comment by youshamahmood96** [comment]
okay.
Interesting
let me see if i can do that

**Comment by wasifhossain** [comment]
as you have **confirmed that the db schema is now in the desired state**, the only thing that you need to do to fix the output of `rails db:migrate:status` is to delete the existing `db/schema.rb` file from your local env and generate it back from the current db
```
rm db/schema.rb # removes the current schema file
rails db:schema:dump # regenerates it back from the current db snapshot
```

once you have done that, confirm if it worked by running `rails db:migrate:status` again

**Comment by youshamahmood96** [comment]
After removing the schema and running it again as suggested.
two things happened.
1.My site is crashing as it is saying that I have duplicate column names.
2. my rails db:migrate:status output:
 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20201126143506  ********** NO FILE **********
   up     20201126144354  Create articles1
   up     20201126144911  Add timestamps to articles
   up     20201129001751  Create users
   up     20201129010520  Add user id to articles
   up     20201129223258  ********** NO FILE **********
   up     20201130055004  Add admin to users
  down    20201130084851  Add password
still the same]

**Comment by wasifhossain** [comment]
that confirms your local db is NOT in desired state as you expected (though I believe the heroku db is ok)

**Comment by youshamahmood96** [comment]
Did these:
1.`rails db:migrate:status`
Fetched the orphaned columns manually.
2. `rails dbconsole`
Went into the console
3. `delete from schema_migrations where version='[version_number]'`
Deleted them manually.
4.Ran the migration and its working fine. No orphaned column anymore.

**Comment by wasifhossain** [comment]
> 3. `delete from schema_migrations where version='[version_number]'`
> Deleted them manually.

that was the trick to resolve this issue. usually you won't ever have to touch the `schema_migrations` table if you follow https://github.com/ormprog/rails_ama/issues/137#issuecomment-735638904
