### ISSUE TITLE
File to import not found or unreadable: ~arctic_admin/src/scss/main

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#139]
instruction follow link; https://github.com/cprodhomme/arctic_admin

first, add `gem 'arctic_admin'` into my gemfile
then run `bundle install --without production`

second, in this `config/initializers/active_admin.rb` file 
add below line

> meta_tags_options = { viewport: 'width=device-width, initial-scale=1' }
> config.meta_tags = meta_tags_options
> config.meta_tags_for_logged_out_pages = meta_tags_options

**Comment by ansary14-zz** [comment]
https://github.com/cprodhomme/arctic_admin#css
here they say in `active_admin.css` file 
add below line 

> /*
>  *= require arctic_admin/base
>  */

**but i don't have `active_admin.css` file in my repo**

**Comment by ansary14-zz** [comment]
https://github.com/cprodhomme/arctic_admin#sass-support
Remove the line `@import "active_admin/base"`   

then add into **active_admin.sass** file 
 

> `@import "arctic_admin/base";` 

then add into **active_admin.js** file

> //= require arctic_admin/base

Remove the line `//= require active_admin/base `

**Comment by ansary14-zz** [comment]
https://github.com/cprodhomme/arctic_admin#use-with-webpacker

Install the needed assets with npm or yarn:
run the command
`yarn add arctic_admin @fortawesome/fontawesome-free`

**Comment by ansary14-zz** [comment]
https://github.com/cprodhomme/arctic_admin#2---css

in your `app/javascript/stylesheets/active_admin.scss`, add the line:

> > 
> @import '~arctic_admin/src/scss/main';
> 

**but i don't have such path**
**i have `app/assets/stylesheets/active_admin.scss`**

**Comment by ansary14-zz** [comment]
https://github.com/cprodhomme/arctic_admin#3---js

Search for `app/javascript/packs/active_admin.js` in your rails project and add the following lines:

> import "@fortawesome/fontawesome-free/css/all.css";
> import 'arctic_admin

**here also i don't have such path
i have `app/assets/javascripts/active_admin.js`**

**Comment by wasifhossain** [comment]
lets try making it work under assets pipeline (i.e skip following webpacker for now)

**Comment by ansary14-zz** [comment]
after skip following webpacker part

the `http://localhost:3000/admin/admin_users`
says like that
![Screenshot from 2021-01-04 18-25-46](https://user-images.githubusercontent.com/33208962/103535103-5dd42580-4eba-11eb-9288-316634cc9a3e.png)

**Comment by ansary14-zz** [comment]
**but i don't see the icon here**
