### ISSUE TITLE
I can't find ssh key 

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#14]
In my tutorials they used below command for display the **ssh key**.
_cat ~/.ssh/id_rsa.pub_
They(tutorials) use **nitrous ide** platform and **cloud 9**. I am using **atom** platform.
when i command, provided one. It says (in picture)
![Screenshot from 2020-01-19 23-39-33](https://user-images.githubusercontent.com/33208962/72727047-22aaea80-3bb4-11ea-9d89-5948015efb89.png)
I cant display the ssh key. It needed for setup GitHub repository.

**Comment by ansary14-zz** [comment]
In my tutorials, they display the **ssh key** via same command. 
Here is a snapshot of my tutorials ...
![Screenshot from 2020-01-20 18-48-23](https://user-images.githubusercontent.com/33208962/72727662-b0d3a080-3bb5-11ea-8905-f4943f57dd82.png)

**Comment by wasifhossain** [comment]
it means that they have already setup an ssh key, which I assume **you have not done** yet.

you may follow the tutorial how to setup an ssh key or follow the following articles from github:

**Checking for existing SSH keys**: https://help.github.com/en/github/authenticating-to-github/checking-for-existing-ssh-keys

**Generating a new SSH key and adding it to the ssh-agent**: https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Let me know if it helps

**Comment by ansary14-zz** [comment]
issue solved.
