### ISSUE TITLE
How to decode this string "ZW1haWwgbWUgYXQgaXJmYW5AaG9pZm9vLmNvbQo=" ?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#140]

**Comment by wasifhossain** [comment]
if a string is encoded using `base64` algorithm, you can decode it using
```rb
require 'base64'

Base64.decode64("<enter-the-string>")
```

Ruby 2.7.2 doc: https://ruby-doc.org/stdlib-2.7.2/libdoc/base64/rdoc/Base64.html

**Comment by sadmanahmed** [comment]
Ah I find that but thrown error
```
require "mail"
s= "ZW1haWwgbWUgYXQgaXJmYW5AaG9pZm9vLmNvbQo="

Mail::Encodings.value_decode(s)
```

**Comment by sadmanahmed** [comment]
Thank you vaia.Solved

**Comment by wasifhossain** [comment]
sorry don't get you. did you get error with my snippet, or yours?

**Comment by sadmanahmed** [comment]
Mine...(I was searching how to decode string... so saw both this one and your type soluion `Base64`,so tried 1st one and get this error)
![image](https://user-images.githubusercontent.com/19534210/104046916-ffd17600-520a-11eb-880b-6dd0919a609f.png)
**Your one works fine

**Comment by wasifhossain** [comment]
if you take a closer look at the [source of the `decode64` method](https://ruby-doc.org/stdlib-2.7.2/libdoc/base64/rdoc/Base64.html#method-i-decode64), you will see this:
```rb
def decode64(str)
  str.unpack1("m")
end
```

so basically, you could decode the string with ruby's builtin [`String#unpack1` method](https://ruby-doc.org/core-2.7.2/String.html#method-i-unpack1)
