### ISSUE TITLE
How I add this `active_admin_comments` table after accidently rollback

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#141]
![Screenshot from 2021-01-31 22-42-53](https://user-images.githubusercontent.com/33208962/106453539-abd94a80-64b3-11eb-9e0a-fd394a5abf23.png)

After creating the `products` table through the AR migration.
It solved the above error.

But then I run  `rake db:rollback STEP=1` 
I want to rollback the latest migration

But it seems it rollback the latest previous one which is `create_active_admin_comments`
For that, the below error shows:
![Screenshot from 2021-02-01 00-42-45](https://user-images.githubusercontent.com/33208962/106454190-931d6480-64b4-11eb-8809-fce8a7183dde.png)

It shows that error because I don't run the migration `rails db:migrate` after creating the `products` table.
And when I run the rollback command it rollback the latest one which was `create_active_admin_comments`

Now, 
When I run the `rails db:migrate` it seems removing the `active_admin_comments` table from `db/schema.rb`
My question is How I add this `active_admin_comments` table again?

**Comment by ansary14-zz** [comment]
My database migration status 

```
➜  finance-tracker git:(master) ✗ rails db:migrate:status

database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20201105180300  Devise create users
   up     20201108130524  Create stocks
   up     20201115141726  Create user stocks
   up     20201126110223  Add first last name to user
   up     20201208165950  Create friendships
   up     20210103211209  Devise create admin users
   up     20210103211212  Create active admin comments
  down    20210201142237  Products
```

**Comment by ansary14-zz** [comment]
![Screenshot from 2021-02-01 19-06-39](https://user-images.githubusercontent.com/33208962/106462872-d7166680-64c0-11eb-922a-a1cd78a1f384.png)

**Comment by wasifhossain** [comment]
as the table already exists in the db, what you can do is

- insert the version 20210201142237 into schema_migrations table
- db:rollback
- remove the products migration, as you dont need it anymore
- remove 20210103211212 from schema_migrations
- db:migrate

**Comment by ansary14-zz** [comment]
How to remove the specific version from schema_migration? 
Any related documentation?

**Comment by ansary14-zz** [comment]
https://github.com/ormprog/rails_ama/issues/137#issuecomment-735970793

Should I run this   `delete from schema_migrations where version='[version_number]'`
**For removing 20210103211212 from schema_migrations**

**Comment by wasifhossain** [comment]
if you are well aware of the consequence, then yes, that command should work
