### ISSUE TITLE
Reached the app limit in Heroku!

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#146]
> ➜  sass-project-app git:(main) heroku create 
> Creating app... !
>  ▸    You've reached the app limit of 5 apps for unverified accounts. Delete
>  ▸    some apps or add a credit card to verify your account.
> ➜  sass-project-app git:(main) 
>

**Comment by wasifhossain** [comment]
you have already got the response, which looks to be clear enough, no?

**Comment by ansary14-zz** [comment]
yes.
I already delete one of my app from Heroku.
then it worked.

**Comment by wasifhossain** [comment]
awesome. please take your time to close any issues once you have it resolved :)
