### ISSUE TITLE
The Ruby version you are trying to install does not exist on this stack!  Heroku push failed!

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#147]
> ➜  sass-project-app git:(main) git push heroku main  
> Enumerating objects: 125, done.
> Counting objects: 100% (125/125), done.
> Delta compression using up to 12 threads
> Compressing objects: 100% (106/106), done.
> Writing objects: 100% (125/125), 153.01 KiB | 3.33 MiB/s, done.
> Total 125 (delta 12), reused 0 (delta 0)
> remote: Compressing source files... done.
> remote: Building source:
> remote: 
> remote: -----> Building on the Heroku-20 stack
> remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
> remote: 			Detected buildpacks: Ruby,Node.js
> remote: 			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
> remote: -----> Ruby app detected
> remote: -----> Installing bundler 1.17.3
> remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
> remote: -----> Compiling Ruby/Rails
> remote:        Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.3.tgz -s -o - | tar zxf - ' failed on attempt 1 of 3.
> remote:        Command: 'set -o pipefail; curl -L --fail --retry 5 --retry-delay 1 --connect-timeout 3 --max-time 30 https://s3-external-1.amazonaws.com/heroku-buildpack-ruby/heroku-20/ruby-2.6.3.tgz -s -o - | tar zxf - ' failed on attempt 2 of 3.
> remote: 
> remote:  !
> remote:  !     The Ruby version you are trying to install does not exist on this stack.
> remote:  !     
> remote:  !     You are trying to install ruby-2.6.3 on heroku-20.
> remote:  !     
> remote:  !     Ruby ruby-2.6.3 is present on the following stacks:
> remote:  !     
> remote:  !     - cedar-14
> remote:  !     - heroku-16
> remote:  !     - heroku-18
> remote:  !     
> remote:  !     Heroku recommends you use the latest supported Ruby version listed here:
> remote:  !     https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
> remote:  !     
> remote:  !     For more information on syntax for declaring a Ruby version see:
> remote:  !     https://devcenter.heroku.com/articles/ruby-versions
> remote:  !
> remote:  !     Push rejected, failed to compile Ruby app.
> remote: 
> remote:  !     Push failed
> remote: Verifying deploy...
> remote: 
> remote: !	Push rejected to ayub-sass-app.
> remote: 
> To https://git.heroku.com/ayub-sass-app.git
>  ! [remote rejected] main -> main (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/ayub-sass-app.git'
>

**Comment by wasifhossain** [comment]
i guess you meant to use `master` and not `main` in the git command, right?

**Comment by ansary14-zz** [comment]
No, I meant to main. 

**because**

> 
> ➜  sass-project-app git:(main) git push heroku master
> error: src refspec master does not match any
> error: failed to push some refs to 'https://git.heroku.com/ayub-sass-app.git'
>

**Comment by ansary14-zz** [comment]
And previously, I push code in the Github repository
as the main branch.

**Comment by wasifhossain** [comment]
alright. heroku already pointed it out:
>remote: ! You are trying to install ruby-2.6.3 on heroku-20.
remote: !
remote: ! Ruby ruby-2.6.3 is present on the following stacks:
remote: !
remote: ! - cedar-14
remote: ! - heroku-16
remote: ! - heroku-18

so either you switch to a lower stack, e.g. heroku-18, or upgrade ruby to something like 2.7.2 or 3.0.0

**Comment by ansary14-zz** [comment]
what is the best option?
**upgrade ruby?**

**Comment by ansary14-zz** [comment]
after upgrading how to set this version as default?

like,
after install `rvm install 2.7.2`
`ruby -v` **it shows 2.7.2**

but after opening a new terminal window it shows **2.6.3**.

**Comment by ansary14-zz** [comment]
should I upgrade from gemfile?
like

instead of 
> ruby '2.6.3'

I write 
>  ruby '2.7.2'


then run bundle install?

**Comment by wasifhossain** [comment]
```
rvm use 2.7.2 --install --default
```
command would use the mentioned ruby version if already is installed and make it as default, otherwise would install it too

**Comment by ansary14-zz** [comment]
https://github.com/ormprog/rails_ama/issues/147#issuecomment-785906272

what about this command

**Comment by wasifhossain** [comment]
> [#147 (comment)](https://github.com/ormprog/rails_ama/issues/147#issuecomment-785906272)
> 
> what about this command

you need that too. unless you specify the ruby version in Gemfile, you won't be able to run `bundle install`

**Comment by ansary14-zz** [comment]
All Done
