### ISSUE TITLE
Oauth error invalid_request: The Shopify API application does not support oauth

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#151]
![Screenshot from 2021-03-09 19-52-55](https://user-images.githubusercontent.com/33208962/110481574-e9b03b00-8111-11eb-8a5f-e39ecfd7f007.png)

**Comment by wasifhossain** [comment]
could you elaborate the process that you followed before ending up with this

**Comment by ansary14-zz** [comment]
after running the `rails server`
visit http://localhost:3000/login
after providing the shop link

it showed the above error.

**Comment by wasifhossain** [comment]
how did you integrate oauth

**Comment by wasifhossain** [comment]
moreover, are you using a public shopify app, right?

**Comment by ansary14-zz** [comment]
no, I am using a private shopify app

**Comment by wasifhossain** [comment]
alright. private app does not support oauth. you need to use public app for that
