### ISSUE TITLE
parse string in ruby

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#152]
My current gsub and the outcome is like this 
```
a="\n Hello abir,                 wss           ,sss              ,ssw s  ,ddd           \n "
puts a.gsub(/\n/,"").strip
``` 
![image](https://user-images.githubusercontent.com/19534210/110780369-d24a8c80-828e-11eb-80d3-2ce92ed4c166.png)

I want to remove the white spaces to I found `\s+` but I cant add them with `\n`

**### Solution found how to add more than one condition**

```
a="\n Hello abir,                 wss           ,sss              ,ssw s  ,ddd           \n "
puts a.gsub(/[\s+\n]/,"").strip
```
![image](https://user-images.githubusercontent.com/19534210/110781008-8b10cb80-828f-11eb-85d7-01b8f863ebf9.png)

**Comment by sadmanahmed** [comment]
But If I want the output like this 
```
Hello abir,wss,sss,ssw s,ddd
```
I want the space between the strings like `hello abir` ,just want to remove all the white space before and after

**Comment by wasifhossain** [comment]
so you like to keep the commas, but remove the whitespaces around it, right?

**Comment by sadmanahmed** [comment]
Yes I want the commas and the space between the string 
I want `   abir is a good boy    ,    abir is cs grad       ` to become `abir is a good boy,abir is cs grad` 
but `s+` will make it `abirisagoodboy,abiriscsgrad`

**Comment by wasifhossain** [comment]
so first you need to split the text by comma. next you need to remove the whitespaces around each of the strings that you get after splitting. finally join those stripped pieces back with comma

```rb
a = "\n Hello abir,                 wss           ,sss              ,ssw s  ,ddd           \n "
a.split(',').map { |s| s.strip }.join(',')
 => "Hello abir,wss,sss,ssw s,ddd"
```

**Comment by sadmanahmed** [comment]
Thanks It worked .
