### ISSUE TITLE
./bin/webpack-dev-server, it shows error Failed to compile

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#155]
> ➜  door_to_door git:(master) ✗ ./bin/webpack-dev-server
> ℹ ｢wds｣: Project is running at http://localhost:3035/
> ℹ ｢wds｣: webpack output is served from /packs/
> ℹ ｢wds｣: Content not from webpack is served from /home/ayub/rails-project/door_to_door/public/packs
> ℹ ｢wds｣: 404s will fallback to /index.html
> ✖ ｢wdm｣: Hash: 597d502cd0adf8f53603
> Version: webpack 4.46.0
> Time: 2474ms
> Built at: 03/16/2021 12:40:05 AM
>                                                  Asset      Size                   Chunks                         Chunk Names
>                 js/application-fe6c97782439dad22326.js  1.02 MiB              application  [emitted] [immutable]  application
>             js/application-fe6c97782439dad22326.js.map  1.18 MiB              application  [emitted] [dev]        application
>         js/stylesheets/_custom-2f6ad02f44f5137ce67e.js   407 KiB      stylesheets/_custom  [emitted] [immutable]  stylesheets/_custom
>     js/stylesheets/_custom-2f6ad02f44f5137ce67e.js.map   457 KiB      stylesheets/_custom  [emitted] [dev]        stylesheets/_custom
>     js/stylesheets/application-25dd5bcd729a9142f988.js  1.03 MiB  stylesheets/application  [emitted] [immutable]  stylesheets/application
> js/stylesheets/application-25dd5bcd729a9142f988.js.map   1.1 MiB  stylesheets/application  [emitted] [dev]        stylesheets/application
>                                          manifest.json  1.15 KiB                           [emitted]              
> 
> ERROR in ./app/javascript/packs/application.js
> Module not found: Error: Can't resolve '../stylesheets/application' in '/home/ayub/rails-project/door_to_door/app/javascript/packs'
> resolve '../stylesheets/application' in '/home/ayub/rails-project/door_to_door/app/javascript/packs'
>   using description file: /home/ayub/rails-project/door_to_door/package.json (relative path: ./app/javascript/packs)
>     Field 'browser' doesn't contain a valid alias configuration
>     using description file: /home/ayub/rails-project/door_to_door/package.json (relative path: ./app/javascript/stylesheets/application)
>       no extension
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application doesn't exist
>       .mjs
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.mjs doesn't exist
>       .js
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.js doesn't exist
>       .sass
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.sass doesn't exist
>       .scss
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.scss doesn't exist
>       .css
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.css doesn't exist
>       .module.sass
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.module.sass doesn't exist
>       .module.scss
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.module.scss doesn't exist
>       .module.css
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.module.css doesn't exist
>       .png
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.png doesn't exist
>       .svg
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.svg doesn't exist
>       .gif
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.gif doesn't exist
>       .jpeg
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.jpeg doesn't exist
>       .jpg
>         Field 'browser' doesn't contain a valid alias configuration
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.jpg doesn't exist
>       as directory
>         /home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application doesn't exist
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.mjs]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.js]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.sass]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.scss]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.css]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.module.sass]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.module.scss]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.module.css]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.png]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.svg]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.gif]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.jpeg]
> [/home/ayub/rails-project/door_to_door/app/javascript/stylesheets/application.jpg]
> ℹ ｢wdm｣: Failed to compile.
>

**Comment by ansary14-zz** [comment]
Here is the error log

**Comment by wasifhossain** [comment]
as its complaining:
>ERROR in ./app/javascript/packs/application.js
Module not found: Error: Can't resolve '../stylesheets/application' in '/home/ayub/rails-project/door_to_door/app/javascript/packs'

could you share the content of `app/javascript/packs/application.js`

**Comment by ansary14-zz** [comment]
```
// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.

require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")


// Uncomment to copy all static images under ../images to the output folder and reference
// them with the image_pack_tag helper in views (e.g <%= image_pack_tag 'rails.png' %>)
// or the `imagePath` JavaScript helper below.
//
// const images = require.context('../images', true)
// const imagePath = (name) => images(name, true)
require("shopify_app")

import 'bootstrap'
import '../stylesheets/application'
```

**Comment by wasifhossain** [comment]
```js
import '../stylesheets/application'
```

this line is causing the error!

could you elaborate why do you need to refer that file from `app/assets/` directory

**Comment by wasifhossain** [comment]
sorry I mean do you have the referenced file under `app/javascript/stylesheets/application.css`

**Comment by wasifhossain** [comment]
also could you share the output of the following commands:
- `tree app/javascript`
- `tree app/assets/stylesheets`

**Comment by ansary14-zz** [comment]
```
➜  door_to_door git:(master) ✗ tree app/javascript
zsh: command not found: tree
➜  door_to_door git:(master) ✗ tree app/assets/stylesheets
zsh: command not found: tree
```

**Comment by wasifhossain** [comment]
```
sudo apt install tree
```

**Comment by ansary14-zz** [comment]
```
➜  door_to_door git:(master) ✗ tree app/javascript        
app/javascript
├── channels
│   ├── consumer.js
│   └── index.js
├── packs
│   ├── application.js
│   └── stylesheets
│       ├── application.scss
│       └── _custom.scss
└── shopify_app
    ├── flash_messages.js
    ├── index.js
    └── shopify_app.js

4 directories, 8 files
➜  door_to_door git:(master) ✗ tree app/assets/stylesheets
app/assets/stylesheets
└── application.css

0 directories, 1 file

```

**Comment by wasifhossain** [comment]
did you copy the contents of `app/assets/stylesheets/application.css` into `app/javascript/packs/stylesheets/application.scss`?

**Comment by ansary14-zz** [comment]
In the following documents https://adrian-teh.medium.com/ruby-on-rails-6-with-webpacker-and-bootstrap-step-by-step-guide-41b52ef4081f

```
require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")

import 'bootstrap'

import '../stylesheets/application' # Import your application.scss here

document.addEventListener("turbolinks:load", () => {
  $('[data-toggle="tooltip"]').tooltip()
})
```

I am confused with this line!  
import '../stylesheets/application' # Import your application.scss here

**Comment by ansary14-zz** [comment]
> did you copy the contents of `app/assets/stylesheets/application.css` into `app/javascript/packs/stylesheets/application.scss`?

No!

**Comment by wasifhossain** [comment]
```
**import '../stylesheets/application' # Import your application.scss here**
```
its suggesting to use the application css file from `app/javascript`.

so you can move that app css file from `app/assets/stylesheets/` to `app/javascript/stylesheets` and refer this new file in `app/javascript/packs/application.js` as you have already done
```js
import '../stylesheets/application'
```

**Comment by ansary14-zz** [comment]
`app/javascript/packs/stylesheets/application.scss` file is
```
@import "~bootstrap/scss/bootstrap"; // never forget the semicolon at the end
@import "./_custom";

```

**Comment by wasifhossain** [comment]
i see that you are messing up with single dot vs double dot :smile: 
```
import './stylesheets/application' ---> points to app/javascript/packs/stylesheets/application.css
```
VS
```
import '../stylesheets/application' ---> points to app/javascript/stylesheets/application.css
```

**Comment by wasifhossain** [comment]
@ansary14 check my edited comment :)

**Comment by ansary14-zz** [comment]
checked

**Comment by wasifhossain** [comment]
then you should have got the clue to solve the case!

**Comment by ansary14-zz** [comment]
SOLVED! :+1: 

Everything runs Perfectly!

**Comment by ansary14-zz** [comment]
> i see that you are messing up with single dot vs double dot smile
> 
> ```
> import './stylesheets/application' ---> points to app/javascript/packs/stylesheets/application.css
> ```
> 
> VS
> 
> ```
> import '../stylesheets/application' ---> points to app/javascript/stylesheets/application.css
> ```

I create the `application.css` file under `app/javascript/packs/stylesheets` folder
And copy the content from `app/asset/stylesheets/application.css`

then remove the changes from the asset pipeline :100:
