### ISSUE TITLE
Polymorphic Association

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#163]
May I get some suggestion How can I effectively learn about this polymorphic association? Rails guide is not well explained here 
![image](https://user-images.githubusercontent.com/19534210/114302959-53df4580-9aed-11eb-8513-f5d4c7a52f3e.png)
If you kind enough to to breakdown the suggestion task by task,it will be more helpful or As you want to share your experience how to solve this real life project basis tasks (I know how to do task 1,2)

**Comment by sadmanahmed** [comment]
Should not I use `start:date` and `end:date` attributes for task3?

**Comment by sadmanahmed** [comment]
Is this enough?
```
rails g model Experience title:string description:string start_time:date end_time:date experience_type:string exp_id:integer exp_type:string User:references
```
`exp_id:integer` and `exp_type:string` set up the columns in our Experience table which allow for our polymorphic association.

**Comment by wasifhossain** [comment]
## Polymorphic Association

based on the experience types, we can see that, for example, a `work` instance could have a list of `experience`s. similarly, `education` and `volunteer` instances could also have a list of `experience`s.

on the inverse side, an `experience` instance would either belong to a `work`, `education` or `volunteer` or any other models as needed.

so let's define the following 2 columns in the `experiences` table:
- `experienceable_type`
- `experienceable_id`
(you could use any prefix in place of `experienceable`, but make sure to apply the convention in the models too)

```rb
create_table :experiences do |t|
  ...
  t.column :experienceable_type, :string
  t.column :experienceable_id, :bigint
  ...
end

add_index :experiences, %i[experienceable_type experienceable_id]
```

you could simplify the polymorphic migration using [`t.references`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-add_reference) as:
```rb
create_table :experiences do |t|
  ...
  t.references :experienceable, polymorphic: true # remember to change the field name if you prefer to use a different prefix
  ...
end
```

as we are done with the migration, let's move to change the models.

```rb
class Experience < ApplicationRecord
  belongs_to :experienceable, polymorphic: true
end

class Education < ApplicationRecord
  has_many :experiences, as: :experienceable
end

class Work < ApplicationRecord
  has_many :experiences, as: :experienceable
end

class Volunteer < ApplicationRecord
  has_many :experiences, as: :experienceable
end
```
