### ISSUE TITLE
How to do versioning when I edit my data in a rails app

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#164]
Here my task is to have versioning for every data,so that user can see the previous datas also.. How can I do this?
![image](https://user-images.githubusercontent.com/19534210/114384741-f01e5080-9bb0-11eb-8be4-9df33c8252c7.png)

**Comment by sadmanahmed** [comment]
it is like I set my name `Abir`, later I changed it to `Md Sadman Ahmed` . So how can I keep this whole record. Like here in github ,if I edit something I can see all the previous versions. 
I have to do same for this task

**Comment by wasifhossain** [comment]
okay, so tracking older versions against some timeline requires more explicit definition of the fields that you want to track.

the example that you mentioned regarding github works for the `comment` field. so every user can leave a comment as well as update any existing comment. every change in `comment` field is tracked against time in a different model

**Comment by wasifhossain** [comment]
if you want to track every field, then you need to plan accordingly

**Comment by wasifhossain** [comment]
you may check the [`logidze`](https://rubygems.org/gems/logidze) gem to enable versioning

**Comment by sadmanahmed** [comment]
> you may check the [`logidze`](https://rubygems.org/gems/logidze) gem to enable versioning

Okay let me check and I will give update you on this.Thanks
