### ISSUE TITLE
Code auto syntaxing in Sublime

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#165]
Is there any gem/library for sublime that will auto resolve any syntax errors in my ruby codes. I tried to install rubocop.. but it is not behaving as I want.
I works well in the terminal when I write `rubocop` this throws with many lines above it.
```
.
.
47 files inspected, 233 offenses detected, 215 offenses auto-correctable

```
But in rubymine and vs code ,that setting is automated (highlighting and auto solving the syntax errors)

**Comment by wasifhossain** [comment]
not sure if sublime works with automatic rubocop execution. 

(personally I don't prefer to autofix any rubocop issues unless they are very straightforward, like `frozen_string_literal missing error` etc.)

**Comment by sadmanahmed** [comment]
Today I give a pull request in our code repo... So I get plenty of comments for white spaces.. So a senior of mine suggested to use syntax fixer

**Comment by sadmanahmed** [comment]
https://www.botreetechnologies.com/blog/integrate-rubocop-gem-popular-ruby-text-editors/ 
I read this article.. it shows the automation ,followed this but no outcome came

**Comment by wasifhossain** [comment]
as you have just started out, I would suggest you to run rubocop and fix each issue manually, from the command line. in that way, you would get a chance to learn these stuffs hands-on.

automation helps them who are highly expert in the field. so reducing the time by auto-fixing the issues would make sense for them

**Comment by wasifhossain** [comment]
i am with Rails for 5+ years, still running it manually. thats how I feel comfort :smile:

**Comment by sadmanahmed** [comment]
okay thanks

**Comment by wasifhossain** [comment]
to fix trivial issues like adding `frozen_string_literal: true` on the 1st line, I run `bundle exec rubocop --auto-correct`.

for non-trivial fixes, I don't prefer to auto-correct them
