### ISSUE TITLE
rake vs rails

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#166]
in any rails 6 project is there any difference between these 2 commands
```
bundle exec rake db:migrate 
vs 
rails db:migrate
```
I googled but the answers were not satisfying

**Comment by wasifhossain** [comment]
- `rails` cli works as a proxy to `rake` cli. so they are similar (at least since Rails 5.0): https://guides.rubyonrails.org/5_0_release_notes.html#railties-notable-changes
- `bundle exec` runs the command that follows it using the gem versions that are mentioned in Gemfile.lock

**Comment by wasifhossain** [comment]
to learn more about what **rake** is, check the following references:

- RAKE – Ruby Make: https://ruby-doc.org/core-2.7.3/gems/rake-13_0_1/README_rdoc.html
- Rakefile Format: https://ruby-doc.org/core-2.7.3/gems/rake-13_0_1/doc/rakefile_rdoc.html
- Custom Rake Tasks: https://guides.rubyonrails.org/command_line.html#custom-rake-tasks

**Comment by wasifhossain** [comment]
to learn more about `bundle exec` command, check https://bundler.io/v2.2/man/bundle-exec.1.html
