### ISSUE TITLE
How to Open Rails credentials in Editors? (With Solution)

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#167]
We need to set credentials like api key/passwords in the rails code but this are very private info and we dont want to share them the github repository. So we need to put the in the credentials files against a symbol and lated use that symbol in the code.
So how can we open the the credentials as it's cant not be open directly.
We can follow this steps
### For Sublime
**Step 1**
```
EDITOR='subl --wait' rails credentials:edit
``` 
### For VS code
**Step 1**
```
EDITOR='code --wait' rails credentials:edit
``` 
### For Rubymine
**Step 1**
```
EDITOR="mine --wait" rails credentials:edit
```

This will open the editor, you have to write down the credentials . E.G.
```
 aws:
   access_key_id: 123
   secret_access_key: 345
```

If the Sublime code does not open the window for editing the credentials rather automatic reply like `File encrypted and saved. ` comes, then We have to do this
### For Sublime
**Step 2**
```
ln -sv "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

EDITOR='subl --wait' rails credentials:edit
```

**I havenot tried the output off rubymine and vscode here**

**Comment by wasifhossain** [comment]
to save from setting the env var every time when you run the command, you can export it to your .bashrc/.zshrc file like this
```
export EDITOR='subl --wait'
```

after that, you can run the command as: `rails credentials:edit`, and it would use Sublime to open the credentials file.
