### ISSUE TITLE
How to open zsh config file |  Switching from Bash to Oh-My-Zsh

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#169]
Every time I created a new rails app, I faced a problem with **node**! 
Like I checking **node version** by running `node -v` It shows like _10.19.0_

Then visit this link https://github.com/nvm-sh/nvm 
to (install) or **Update** the _nvm_ 
by running
 `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash`
 It suggest me to run 
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
 After running the above command, I check the `node -v` it shows updated one _14.15.4_
 
 But the problem is when I **close the current terminal** and **open a new terminal**, it shows the **node version old one**. Like _10.19.0_ !

Then again run the **export command**, it changed the **node -v into updated one** _14.15.4_

**Comment by wasifhossain** [comment]
you can persist the settings on ZSH config file, found at `~/.zshrc`, by opening with an editor, e.g. sublime
```
subl ~/.zshrc
```
and paste the following content at the end of that file
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```
