### ISSUE TITLE
no matches found: postcss@^7

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#170]
I am facing a problem to install tailwind css
I follow this video https://www.youtube.com/watch?v=6UT0dRmGFOM&t

1.  I follow instruction from  https://tailwindcss.com/docs/installation 
2. And setup tailwind CSS But at the last moment it shows an error
**Error: PostCSS plugin tailwindcss requires PostCSS 8.**

3. Then they suggest https://tailwindcss.com/docs/installation#post-css-7-compatibility-build 
I follow their instruction 

4. First, I uninstall Tailwind by running `yarn remove tailwindcss postcss autoprefixer`
5. Then run the install command 
`yarn add tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9`

Unfortunately It also show an error  `zsh: no matches found: postcss@^7`

**Comment by wasifhossain** [comment]
you need to prefix caret `^` with backslash `\`. so valid command would be:
```
yarn add tailwindcss@npm:@tailwindcss/postcss7-compat postcss@\^7 autoprefixer@\^9
```
