### ISSUE TITLE
Stripe hidden value is not passing

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#175]
I have setuo the stripe as the official doc and udemy course says
**config/initializer/stripe.rb**
```
Rails.configuration.stripe = {
  :publishable_key => ENV['STRIPE_TEST_PUBLISHABLE_KEY'],
  :secret_key      => ENV['STRIPE_TEST_SECRET_KEY']
}
Stripe.api_key = Rails.configuration.stripe[:secret_key]
```

Placed the stripe hidden values as instructed(the sendgrid is also placed here and they are working fine)
**.profile**
```
export SENDGRID_USERNAME=apikey
export SENDGRID_PASSWORD=**
export STRIPE_TEST_PUBLISHABLE_KEY=**
export STRIPE_TEST_SECRET_KEY=**
```
**But it is not showing the value in rails console,so the value is not passing**
```
2.7.2 :002 > Rails.configuration.stripe[:secret_key]
 => nil 

```
So when I am trying to signup ,this error is showing which is obvious that it is not getting the value from **.profile to stripe.rb**
![](https://files.slack.com/files-pri/T940F41R9-F02686M2F2R/image.png)

**Comment by sadmanahmed** [comment]
![](https://files.slack.com/files-pri/T940F41R9-F02686M2F2R/image.png)

**Comment by sadmanahmed** [comment]
![image (2)](https://user-images.githubusercontent.com/19534210/123667697-3607be00-d85c-11eb-8944-ccd3f15bc303.png)

**Comment by wasifhossain** [comment]
`.profile` is not a good place to store your project-specific environment variables. let's use https://direnv.net/ for the purpose

**Comment by sadmanahmed** [comment]
okay this problem solved with arising another problem
