### ISSUE TITLE
Sign in Routing

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#2]
How can I create the routes by my owns in a different project? 
Code given in slack channel

**Comment by wasifhossain** [comment]
can you please update the post with the code sample that you tried so far

**Comment by sadmanahmed** [comment]
I get confused in this actually

```rb
# config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end
```

**Comment by wasifhossain** [comment]
https://guides.rubyonrails.org/routing.html should help

**Comment by sadmanahmed** [comment]
Why this error is throughing out when I am trying to push the basic login codes 

 sample_app git:(master) git push heroku
Enumerating objects: 65, done.
Counting objects: 100% (65/65), done.
Delta compression using up to 4 threads
Compressing objects: 100% (35/35), done.
Writing objects: 100% (37/37), 5.51 KiB | 2.75 MiB/s, done.
Total 37 (delta 19), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.6.2
remote: -----> Installing dependencies using bundler 1.17.3
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
remote:        Using rake 12.3.3
remote:        Using concurrent-ruby 1.1.5
remote:        Using i18n 1.6.0
remote:        Using minitest 5.11.3
remote:        Using thread_safe 0.3.6
remote:        Using tzinfo 1.2.5
remote:        Using zeitwerk 2.1.10
remote:        Using activesupport 6.0.0
remote:        Using builder 3.2.3
remote:        Using erubi 1.8.0
remote:        Using mini_portile2 2.4.0
remote:        Using nokogiri 1.10.4
remote:        Using rails-dom-testing 2.0.3
remote:        Using crass 1.0.4
remote:        Using loofah 2.2.3
remote:        Using rails-html-sanitizer 1.2.0
remote:        Using actionview 6.0.0
remote:        Using rack 2.0.7
remote:        Using rack-test 1.1.0
remote:        Using actionpack 6.0.0
remote:        Using nio4r 2.5.1
remote:        Using websocket-extensions 0.1.4
remote:        Using websocket-driver 0.7.1
remote:        Using actioncable 6.0.0
remote:        Using globalid 0.4.2
remote:        Using activejob 6.0.0
remote:        Using activemodel 6.0.0
remote:        Using activerecord 6.0.0
remote:        Using mimemagic 0.3.3
remote:        Using marcel 0.3.3
remote:        Using activestorage 6.0.0
remote:        Using mini_mime 1.0.2
remote:        Using mail 2.7.1
remote:        Using actionmailbox 6.0.0
remote:        Using actionmailer 6.0.0
remote:        Using actiontext 6.0.0
remote:        Using execjs 2.7.0
remote:        Using autoprefixer-rails 9.6.4
remote:        Using bcrypt 3.1.13
remote:        Using msgpack 1.3.1
remote:        Using bootsnap 1.4.5
remote:        Using ffi 1.11.1
remote:        Using sassc 2.2.1
remote:        Using bootstrap-sass 3.4.1
remote:        Using bundler 1.17.3
remote:        Using jbuilder 2.9.1
remote:        Using method_source 0.9.2
remote:        Using pg 1.1.4
remote:        Using puma 3.12.1
remote:        Using rack-proxy 0.6.5
remote:        Using thor 0.20.3
remote:        Using railties 6.0.0
remote:        Using sprockets 3.7.2
remote:        Using sprockets-rails 3.2.1
remote:        Using rails 6.0.0
remote:        Using rb-fsevent 0.10.3
remote:        Using rb-inotify 0.10.0
remote:        Using sass-listen 4.0.0
remote:        Using sass 3.7.4
remote:        Using tilt 2.0.9
remote:        Using sass-rails 5.1.0
remote:        Using turbolinks-source 5.2.0
remote:        Using turbolinks 5.2.0
remote:        Using webpacker 4.0.7
remote:        Bundle complete! 27 Gemfile dependencies, 64 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Bundle completed (0.49s)
remote:        Cleaning up the bundler cache.
remote:        The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
remote: -----> Installing node-v10.15.3-linux-x64
remote: -----> Installing yarn-v1.16.0
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        yarn install v1.16.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.2.9: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > webpack-dev-server@3.8.1" has unmet peer dependency "webpack@^4.0.0".
remote:        warning "webpack-dev-server > webpack-dev-middleware@3.7.1" has unmet peer dependency "webpack@^4.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 24.47s.
remote:        Compiling…
remote:        Compilation failed:
remote:        /tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/cli.js:93
remote:        				throw err;
remote:        				^
remote:        
remote:        TypeError: environment.toWebpackConfig is not a function
remote:            at Object.<anonymous> (/tmp/build_7cd8141b586f194697f65f61c1a08039/config/webpack/production.js:5:30)
remote:            at Module._compile (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
remote:            at Module.load (internal/modules/cjs/loader.js:600:32)
remote:            at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:531:3)
remote:            at Module.require (internal/modules/cjs/loader.js:637:17)
remote:            at require (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
remote:            at WEBPACK_OPTIONS (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
remote:            at requireConfig (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
remote:            at /tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
remote:            at Array.forEach (<anonymous>)
remote:            at module.exports (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
remote:            at yargs.parse (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/cli.js:71:45)
remote:            at Object.parse (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
remote:            at /tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/cli.js:49:8
remote:            at Object.<anonymous> (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack-cli/bin/cli.js:366:3)
remote:            at Module._compile (internal/modules/cjs/loader.js:701:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
remote:            at Module.load (internal/modules/cjs/loader.js:600:32)
remote:            at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:531:3)
remote:            at Module.require (internal/modules/cjs/loader.js:637:17)
remote:            at require (internal/modules/cjs/helpers.js:22:18)
remote:            at Object.<anonymous> (/tmp/build_7cd8141b586f194697f65f61c1a08039/node_modules/webpack/bin/webpack.js:156:2)
remote:            at Module._compile (internal/modules/cjs/loader.js:701:30)
remote:            at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
remote:            at Module.load (internal/modules/cjs/loader.js:600:32)
remote:            at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
remote:            at Function.Module._load (internal/modules/cjs/loader.js:531:3)
remote:            at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
remote:            at startup (internal/bootstrap/node.js:283:19)
remote:            at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
remote:        
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to obscure-hollows-36531.
remote: 
To https://git.heroku.com/obscure-hollows-36531.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/obscure-hollows-36531.git'
