### ISSUE TITLE
How to add bootstrap on rails 6

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#21]
I just follow this link to add bootstrap.
I followed every instruction 
[https://www.mashrurhossain.com/blog/rails6bootstrap4](url)

When I testing my bootstrap. Its look like not working.
My custom.css.scss not working.
What should i do ?

**Comment by wasifhossain** [comment]
I have also followed the article but got bootstrap working without any issue :tada: 

could you share the changes that you made based on the article

**Comment by ansary15** [comment]
Okay. Now I undo the previous git which I was last updated. Then follow the instructions again.

**Comment by ansary14-zz** [comment]
After passing below command :- 
**Command : _yarn add bootstrap@4.3.1 jquery popper.js_**

`ayub@ayub-MS-7C02:~/Ansary/rails_project/alpha_blog$ yarn add bootstrap@4.3.1 jquer
y popper.js
yarn add v1.21.1
[1/4] Resolving packages...
warning popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this pa
ckage is dedicated to the legacy v1
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Ex
cluding it from installation.
[3/4] Linking dependencies...
warning " > webpack-dev-server@3.10.1" has unmet peer dependency "webpack@^4.0.0 ||
 ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has unmet peer dependen
cy "webpack@^4.0.0".

[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.22.0"
, while you're on "1.21.1".
info To upgrade, run the following command:
$ sudo apt-get update && sudo apt-get install yarn
success Saved 3 new dependencies.
info Direct dependencies
├─ bootstrap@4.3.1
├─ jquery@3.4.1
└─ popper.js@1.16.1
info All dependencies
├─ bootstrap@4.3.1
├─ jquery@3.4.1
└─ popper.js@1.16.1
Done in 2.80s.
ayub@ayub-MS-7C02:~/Ansary/rails_project/alpha_blog$ sudo apt-get update && sudo ap
t-get install yarn
[sudo] password for ayub:
Hit:1 http://mirror.dhakacom.com/ubuntu-archive bionic InRelease
Hit:2 http://mirror.dhakacom.com/ubuntu-archive bionic-updates InRelease
Hit:3 http://mirror.dhakacom.com/ubuntu-archive bionic-backports InRelease
Ign:4 http://mirror.0x.sg/linuxmint tricia InRelease
Hit:5 http://mirror.0x.sg/linuxmint tricia Release
Get:6 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:8 https://deb.nodesource.com/node_12.x bionic InRelease
Hit:9 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:10 http://dl.google.com/linux/chrome/deb stable Release
Err:6 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging
<yarn@dan.cx>
Hit:12 http://archive.canonical.com/ubuntu bionic InRelease
Fetched 17.1 kB in 1s (15.4 kB/s)
Reading package lists... Done

W: An error occurred during the signature verification. The repository is not updat
ed and the previous index files will be used. GPG error: https://dl.yarnpkg.com/deb
ian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B6
3E1E Yarn Packaging <yarn@dan.cx>
W: Failed to fetch https://dl.yarnpkg.com/debian/dists/stable/InRelease  The follow
ing signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx
>
W: Some index files failed to download. They have been ignored, or old ones used in
stead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
yarn is already the newest version (1.21.1-1).
The following packages were automatically installed and are no longer required:
  libc-ares2 libhttp-parser2.7.1 libllvm8:i386 libuv1 linux-headers-4.15.0-72
  linux-headers-4.15.0-72-generic linux-headers-4.15.0-74
  linux-headers-4.15.0-74-generic linux-headers-4.15.0-76
  linux-headers-4.15.0-76-generic linux-headers-5.0.0-37
  linux-headers-5.0.0-37-generic linux-headers-5.3.0-26
  linux-headers-5.3.0-26-generic linux-image-4.15.0-72-generic
  linux-image-4.15.0-74-generic linux-image-4.15.0-76-generic
linux-image-5.0.0-37-generic linux-image-5.3.0-26-generic
  linux-modules-4.15.0-72-generic linux-modules-4.15.0-74-generic
  linux-modules-4.15.0-76-generic linux-modules-5.0.0-37-generic
  linux-modules-5.3.0-26-generic linux-modules-extra-4.15.0-72-generic
  linux-modules-extra-4.15.0-74-generic linux-modules-extra-4.15.0-76-generic
  linux-modules-extra-5.0.0-37-generic linux-modules-extra-5.3.0-26-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`

**Comment by ansary14-zz** [comment]
Then `package.json` file changed like below (ss)
![package_jason](https://user-images.githubusercontent.com/33208962/75092654-3925d680-55a4-11ea-9e6d-52d8830291d8.png)

**Comment by ansary14-zz** [comment]
Then changed `config/webpack/environment.js` file look like below(ss):
![environment_js](https://user-images.githubusercontent.com/33208962/75092727-d5e87400-55a4-11ea-8578-1b7436d62483.png)

**Comment by ansary14-zz** [comment]
Then add _import bootstrap command_  into `app/javascript/packs/application.js` file(ss).
![application_js](https://user-images.githubusercontent.com/33208962/75092777-8b1b2c00-55a5-11ea-864a-bb224e381f47.png)

**Comment by ansary14-zz** [comment]
Then add _***= require bootstrap**_ into `app/assets/stylesheets/application.css` file (ss):
![application_css](https://user-images.githubusercontent.com/33208962/75092850-3926d600-55a6-11ea-9f7e-3352415c6e41.png)

**Comment by ansary14-zz** [comment]
Then import bootstrap library into `app/assets/stylesheets/custom.css.scss` file(ss):
![custom_css_scss](https://user-images.githubusercontent.com/33208962/75092920-0d582000-55a7-11ea-8da4-7b95eb074a5e.png)

**Comment by ansary14-zz** [comment]
Now it works :+1:  
I don't know why it didn't work before.

**Comment by ansary14-zz** [comment]
Thanks @wasifhossain vai . Its magically worked :100:
