### ISSUE TITLE
ActiveStorage::InvariableError while resizing image

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#23]
I have made a helping method (**display_image** method)in the micropost.rb file and fetch that method in the _micropost.html.erb file from it
**micropost.rb**
```
class Micropost < ApplicationRecord
  belongs_to       :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size: { less_than: 5.megabytes,
                            message:     "should be less than 5MB" }

  # Returns a resized image for display.
  **def display_image**
    **image.variant(resize_to_limit: [500, 500])**
  **end**
end

```
**_micropost.html.erb**
```
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.**display_image** if micropost.image.attached? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

```
(the block parts are added , before adding this the code worked fine and also working fine when I removed them. I am following the tutorial, the code are 100% same as in the tutorial, installed all the gems required)
![ss](https://user-images.githubusercontent.com/19534210/75098899-c3daf580-55e5-11ea-808b-da5f52fd7fc3.png)

**Comment by wasifhossain** [comment]
can you highlight what do you mean by the block part

**Comment by sadmanahmed** [comment]
# Returns a resized image for display.
  **def display_image**
    **image.variant(resize_to_limit: [500, 500])**
  **end**

**Comment by sadmanahmed** [comment]
<%= image_tag micropost.**display_image** if micropost.image.attached? %>
  </span>

**Comment by sadmanahmed** [comment]
I have added a new method display_image but it is not working as the error is given on above,the localhost server has been restarted few times but the error message is same.

**Comment by wasifhossain** [comment]
can you share the version that worked before

**Comment by sadmanahmed** [comment]
_microsoft.html.erb
```
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.image if micropost.image.attached? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= link_to "delete", micropost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>
```
micropost.rb
```
class Micropost < ApplicationRecord
  belongs_to       :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size: { less_than: 5.megabytes,
                            message:     "should be less than 5MB" }

  
end

```

Code works fine here but when I am trying to add the image resizing option (code shared above), error happens

**Comment by wasifhossain** [comment]
i see. before you were calling `micropost.image`, but now you are calling `micropost.image.variant(resize_to_limit: [500, 500])`

can you try the 2nd case on rails console and see what error you get. most probably it would be same as the one posted above: `ActiveStorage::InvariableError`

please confirm the case

**Comment by sadmanahmed** [comment]
```
SyntaxError (/home/abir/environment/sample_app/app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
  def display_image
      ^~~~~~~~~~~~~
/home/abir/environment/sample_app/app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input):
  
app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
app/controllers/static_pages_controller.rb:5:in `home'
```

**Comment by wasifhossain** [comment]
according to [`ActiveStorage::Blob#variant`](https://api.rubyonrails.org/classes/ActiveStorage/Blob/Representable.html#method-i-variant) reference, 

> `ActiveStorage::InvariableError` is raised if ImageMagick cannot transform the blob. To determine whether a blob is variable, call `ActiveStorage::Blob#variable?`

So you could only call the variant method if variable? returns true, otherwise just return the image, which would work as before.

```rb
def display_image
  image.variable? ? image.variant(resize_to_limit: [500, 500]) : image
end
```

**Comment by sadmanahmed** [comment]
Sorry,have not get you

**Comment by wasifhossain** [comment]
> ```
> SyntaxError (/home/abir/environment/sample_app/app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
>   def display_image
>       ^~~~~~~~~~~~~
> /home/abir/environment/sample_app/app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input):
>   
> app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
> app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
> app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
> app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
> app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
> app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
> app/controllers/static_pages_controller.rb:5:in `home'
> ```

the above log is only helpful to debug when its accompanied with the source code that the log is referring to

**Comment by wasifhossain** [comment]
> Sorry,have not get you

try this as your new block of code in the micropost.rb file
```rb
def display_image
  image.variable? ? image.variant(resize_to_limit: [500, 500]) : image
end
```

**Comment by sadmanahmed** [comment]
```
Started GET "/" for ::1 at 2020-02-24 00:28:22 +0600
Processing by StaticPagesController#home as HTML
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/helpers/sessions_helper.rb:18:in `current_user'
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.5ms | Allocations: 2017)


  
SyntaxError (/home/abir/environment/sample_app/app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
  def display_image
      ^~~~~~~~~~~~~
/home/abir/environment/sample_app/app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input):
  
app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input
app/controllers/static_pages_controller.rb:5:in `home'

```

**Comment by wasifhossain** [comment]
according to the error log
> SyntaxError (/home/abir/environment/sample_app/app/models/micropost.rb:13: syntax error, unexpected tIDENTIFIER, expecting '.' or &. or :: or '['
  def display_image
      ^~~~~~~~~~~~~
/home/abir/environment/sample_app/app/models/micropost.rb:16: syntax error, unexpected end, expecting end-of-input):

can you share micropost.rb, which is supposed to contain the syntax error as pointed out by the log

**Comment by sadmanahmed** [comment]
```
class Micropost < ApplicationRecord
  belongs_to       :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image,   content_type: { in: %w[image/jpeg image/gif image/png],
                                      message: "must be a valid image format" },
                      size: { less_than: 5.megabytes,
                            message:     "should be less than 5MB" }

   Returns a resized image for display.
  def display_image
  image.variable? ? image.variant(resize_to_limit: [500, 500]) : image
end
end

```

**Comment by sadmanahmed** [comment]
okay code is running okay now

**Comment by sadmanahmed** [comment]
forgot to comment out the comment

**Comment by wasifhossain** [comment]
please close the issue if you think its resolved by now :)

**Comment by sadmanahmed** [comment]
what this actually means ? 
```
image.variable? ? image.variant(resize_to_limit: [500, 500]) : image
```
and differ from 

```
    image.variant(resize_to_limit: [500, 500])
 
```

**Comment by wasifhossain** [comment]
> what this actually means ?
> 
> ```
> image.variable? ? image.variant(resize_to_limit: [500, 500]) : image
> ```

first of all, ternary operator `? :` is used here, which is shorthand for writing as
```rb
if image.variable?
  image.variant(resize_to_limit: [500, 500])
else
  image
end
```

> 
> and differ from
> 
> ```
>     image.variant(resize_to_limit: [500, 500])
>  
> ```

the logic is already explained in https://github.com/ormprog/rails_ama/issues/23#issuecomment-590099942

to repeat: 

`variant` method only works if ImageMagick can transform the blob. To know the case, you have to call another method called `variable?`

if the method returns false, then you would like to return the original blob instead of the transformed version, so `image` is returned

**Comment by wasifhossain** [comment]
is it solved?
