### ISSUE TITLE
Heroku push failed because a pushed branch tip is behind its remote counterpart

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#25]
I want to push my current branch in heroku for testing whether it is working fine on web or not(as per book ), but this error has showed up
```
sample_app git:(user-microposts) git push heroku user-microposts:master                   
To https://git.heroku.com/obscure-hollows-36531.git
 ! [rejected]        user-microposts -> master (non-fast-forward)
error: failed to push some refs to 'https://git.heroku.com/obscure-hollows-36531.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

```

**Comment by wasifhossain** [comment]
are you trying to push local `user-microposts` branch changes to heroku?

**Comment by sadmanahmed** [comment]
yes

**Comment by wasifhossain** [comment]
which branch did you push before to heroku

**Comment by sadmanahmed** [comment]
master always...

**Comment by wasifhossain** [comment]
and whats the parent branch for `user-microposts`

**Comment by sadmanahmed** [comment]
master

**Comment by wasifhossain** [comment]
can you share output of 
```
git log --oneline -n 5 master
```
and
```
git log --oneline -n 10 user-microposts
```

**Comment by sadmanahmed** [comment]
git log --oneline -n 5 master
```
780859f (origin/master, heroku/master, master) Add password reset
d9af8a7 (password-reset) Update
cb36071 (origin/password-reset) Add Password reset
4883ac8 (account-activation-1, account-activation) Add account activation v3
9e1b576 Add account activation V2

```

**Comment by sadmanahmed** [comment]
git log --oneline -n 10 user-microposts

```
c6e43d4 (HEAD -> user-microposts, origin/user-microposts) Add user microposts
d9af8a7 (password-reset) Update
cb36071 (origin/password-reset) Add Password reset
4883ac8 (account-activation-1, account-activation) Add account activation v3
9e1b576 Add account activation V2
358ea17 (origin/account-activation) Add account activation
a79e38c (updating-users, D) Finish user Edit, Update, Index, and Destroy actions
9597003 Implement advanced login
5f59cc2 (advanced-login) Implement advanced login
7c63cc6 Implement basic login

```

**Comment by wasifhossain** [comment]
i see. your current branch is not rebased on `master` yet. lets rebase it first.
```
git checkout user-microposts
git rebase -i master
```
the 2nd command would open a tab on your editor. please share the screenshot before making any further step

## DISCLAIMER

`git-rebase` is a risky operation. you should execute it with care. 

PROS:
- very powerful git command to help git history clean

CONS:
- uninformed execution may delete your commit history :skull_and_crossbones:

things can become complex if the editor is not set in your environment variable, in which case the default **Nano editor** would be used to edit your commits

**Comment by sadmanahmed** [comment]
seems like a very complex place

![ss](https://user-images.githubusercontent.com/19534210/75118519-23e4a100-56a5-11ea-9493-67e7e3770398.png)

**Comment by sadmanahmed** [comment]
> i see. your current branch is not rebased on `master` yet. lets rebase it first.
> 
> ```
> git checkout user-microposts
> git rebase -i master
> ```
> 
> the 2nd command would open a tab on your editor. please share the screenshot before making any further step
> 
> ## DISCLAIMER
> `git-rebase` is a risky operation. you should execute it with care.
> 
> PROS:
> 
> * very powerful git command to help git history clean
> 
> CONS:
> 
> * uninformed execution may delete your commit history skull_and_crossbones
> 
> things can become complex if the editor is not set in your environment variable, in which case the default **Nano editor** would be used to edit your commits

*DANGEROUS*

**Comment by sadmanahmed** [comment]
So now I am sitting on a volcano with HUGE Potentiality of Power

**Comment by wasifhossain** [comment]
> seems like a very complex place
> 
> ![ss](https://user-images.githubusercontent.com/19534210/75118519-23e4a100-56a5-11ea-9493-67e7e3770398.png)

first, lets close the file on **Nano** by pressing `ctrl+x` and `shift+n`. pls share the output upon closing the editor.

its better to use your regular editor to edit git commits.

will post next instructions soon

**Comment by sadmanahmed** [comment]
ctrl+x close the editor already ,should i press both at a same time?( ctrl+x and shift+n)

**Comment by wasifhossain** [comment]
no need. what output did you get upon closing the file

**Comment by sadmanahmed** [comment]
```
Successfully rebased and updated refs/heads/user-microposts.

```

**Comment by wasifhossain** [comment]
ok. we can proceed next to set sublime as our default editor for git.

lets run `git config --global core.editor "subl -w"`

now if you run the rebase command again: `git rebase -i master`, it should open sublime. lets share the ss in that case

**Comment by sadmanahmed** [comment]
![ss](https://user-images.githubusercontent.com/19534210/75118966-01548700-56a9-11ea-869c-e2cb3d1cb4ca.png)

**Comment by wasifhossain** [comment]
you should read the commands mentioned in the editor during git rebase.

for now, all is good as you only have the listed commits since your last commit in master. so you can safely close this file, which should complete the rebase operation.

lets have a look at the git log for this branch again: `git log --oneline -n 10 user-microposts`

**Comment by sadmanahmed** [comment]
should I close it at first(the sublime git version)?

**Comment by sadmanahmed** [comment]
```
baf117b (HEAD -> user-microposts) Add user microposts
780859f (origin/master, heroku/master, master) Add password reset
d9af8a7 (password-reset) Update
cb36071 (origin/password-reset) Add Password reset
4883ac8 (account-activation-1, account-activation) Add account activation v3
9e1b576 Add account activation V2
358ea17 (origin/account-activation) Add account activation
a79e38c (updating-users, D) Finish user Edit, Update, Index, and Destroy actions
9597003 Implement advanced login
5f59cc2 (advanced-login) Implement advanced login

```

**Comment by wasifhossain** [comment]
top 2 commits:
> baf117b (HEAD -> user-microposts) Add user microposts
780859f (origin/master, heroku/master, master) Add password reset

awesome :tada: As the current branch is now originated from the master branch, you should be able to push to heroku at this point :+1: 

so lets try the command in the OP
```
git push heroku user-microposts:master
```

**Comment by sadmanahmed** [comment]
I can not close the the Nano by pressing ctrl+x

**Comment by wasifhossain** [comment]
which command did you use before nano was open

**Comment by sadmanahmed** [comment]
how to exit it...
![ss](https://user-images.githubusercontent.com/19534210/75119235-13372980-56ab-11ea-98ae-61ea7f222f38.png)

**Comment by wasifhossain** [comment]
> how to exit it...
> ![ss](https://user-images.githubusercontent.com/19534210/75119235-13372980-56ab-11ea-98ae-61ea7f222f38.png)

i see. its VIM; not nano.

to close VIM, press `q`

**Comment by sadmanahmed** [comment]
okay it is actually working right now....
