### ISSUE TITLE
Status feed for all

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#28]
Scenario: This bunch of codes enable my website(a similar website like twitter) to make a post , follow/unfollow someone,a status feed where I can have the post/tweets of others whom I am following . 

But If I want to have post of all the other user in the status feed(followed/ not followed) what should I change in the feed ?

app/models/user.rb
 ```
class User < ApplicationRecord
  .
  .
  .
  # Returns a user's status feed.
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  .
  .
  .
end

```

We can write the upper portion also in the below style. Works fine in both code
app/models/user.rb
 ```
class User < ApplicationRecord
  .
  .
  .
 # Returns a user's status feed.
  def feed
    Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
  end
 .
  .
  .
end
```

**Comment by sadmanahmed** [comment]
![final](https://user-images.githubusercontent.com/19534210/76354955-990ad400-633d-11ea-980e-53439a2d5f44.png)
In the event board only the followed id's post are showing, how can I bring all the users post here to?

**Comment by wasifhossain** [comment]
how do the following models associate with each other
- user
- micropost
- relationship

**Comment by sadmanahmed** [comment]
Should I share the codes of this 3 files?

**Comment by wasifhossain** [comment]
ok lets postpone that for now

**Comment by wasifhossain** [comment]
which controller is showing the above page

**Comment by wasifhossain** [comment]
whats the route and the action

**Comment by wasifhossain** [comment]
if you call `Micropost.all`, then it will return all the posts. do you mean this?

**Comment by sadmanahmed** [comment]
https://github.com/ormprog/rails_ama/issues/28#issue-578832367
I have made a little change in the 2nd code portion

**Comment by sadmanahmed** [comment]
https://github.com/ormprog/rails_ama/issues/28#issuecomment-597294498
Yes,I want all the micropost

**Comment by wasifhossain** [comment]
hope you got the answer above

**Comment by sadmanahmed** [comment]
**Micropost.all** can resolve it right?
