### ISSUE TITLE
Create Controller File Using Generator

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#33]
I need to create 4 controller file for the demo API project,they provided the code but didn't provide the controller instruction. I need some reviewing on it. Need 4 controller for the models 1. author.rb 2.book.rb 3.book_copy.rb 4.user.rb 
are the controller sudo code for them are these?
1. rails generate controller Authors 
2. rails generate controller Books
3. rails generate controller Book_Copies
4. rails generate controller Users

Point to be noted
I need to make them like this
1. class AuthorsController < ApplicationController
2.   class BooksController < ApplicationController
3.  class BookCopiesController < ApplicationController
4.   class UsersController < ApplicationController

**Comment by wasifhossain** [comment]
you are almost close! there will be no underscore in Book_Copies

> rails generate controller BookCopies

controller generator signature looks like this:
```
rails generate controller NAME [action action] [options]
```

you can find usage of the generator by running the following command inside a terminal:
```
rails generate controller
```

the same goes for models/scaffolds etc
```
rails generate model
```
```
rails generate scaffold
```

**Comment by sadmanahmed** [comment]
the what will be the correct one for 
```
rails generate controller Book_Copies
```
to generate something like this
```
class BookCopiesController < ApplicationController
.
.
.
```

**Comment by wasifhossain** [comment]
already answered. please check my earlier post again
