### ISSUE TITLE
Rails constant autoloading: file path/name convention

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#39]
From the link https://www.nopio.com/blog/rails-api-active-model-serializers/ I found this instructions to create an UserContext class but the instruction is not clear actually.
Given instruction
```
And here’s one important thing – custom Pundit’s context (overridden pundit_user method).

Let’s first add the UserContext class (to app/policies/contexts):
```
Given code
```
module Contexts
  class UserContext
    attr_reader :user, :admin

    def initialize(user, admin)
      @user = user
      @admin = admin
    end
  end
end
```

**Comment by wasifhossain** [comment]
In Rails, filenames are underscored, while class names are camel-cased.

e.g. if a class/module name is `HowAreYou`, which is camel-cased, the filename should be `how_are_you.rb`

if the file is put under some namespace (directory), e.g. `hello/how_are_you.rb`, then class signature would look like
```rb
module Hello
  class HowAreYou; end
end
```
**namespaces** in Ruby can be either a **class** or a **module**.

## [Autoloading in Rails](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html):

Rails auto-loads all folders under `app` (1st level only), e.g. if the app directory looks like:
```
app
|-- models
    |-- product.rb
|-- controllers
    |-- api
        |-- v1
            |-- products_controller.rb
```

here `models` and `controllers` will be autoloaded; but not `api` nor `api/v1`

let's discuss the 2 files `product.rb` and `products_controller.rb` below in details:
#### product.rb
`product.rb` sits under `app/models`, so the class signature would look like
:heavy_check_mark: 
```rb
class Product
end
```
autoloading implies that you don't have to namespace the app or models. the following **won't** work
:skull:  
```rb
module App
  module Models
    class Product
    end
  end
end
```

#### products_controller.rb
it sits under `app/controllers/api/v1/`. as we already know that `app/controllers` is loaded automatically by Rails, we just need to start namespacing from api. here is the class signature
```rb
module Api
  module V1
    class ProductsController
    end
  end
end
```

**Comment by wasifhossain** [comment]
let me know how it should look like for your case

**Comment by sadmanahmed** [comment]
So I need to create an user_context.rb in this pathway /home/abir/library/app/policies/contexts/, right?
https://github.com/ormprog/rails_ama/issues/39#issue-599508527
