### ISSUE TITLE
How to update Ruby version in an existing app

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#4]

**Comment by wasifhossain** [comment]
if you use `rvm`, then on linux/unix systems, assuming we are going to use Ruby 2.6.5, the process would be:

step 1: `rvm use rvm use 2.6.5 --install --default`
step 2: update `Gemfile` with the line `ruby '2.6.5'`
step 3: run `bundle install` to update gems based on the current ruby version

**Comment by sadmanahmed** [comment]
Facing a problem now with the ruby version .
I am using 2 terminal window . I updated rails version in the main one and it is showing 2.6.5 when writing "ruby -version" but the when I am opening a new terminal by ctrl+shift+t then the version is going back to 2.6.2 for that terminal


Window 1.  sample_app git:(master) ✗ ruby -version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
Traceback (most recent call last):
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)

Window 2. sample_app git:(master) ✗ ./bin/webpack-dev-server
Your Ruby version is 2.6.2, but your Gemfile specified 2.6.5
➜  sample_app git:(master) ✗ ruby -version
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
Traceback (most recent call last):
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)

**Comment by wasifhossain** [comment]
first of all, command to check the ruby version would be: `ruby --version`; note `--`, not `-`

`ruby -v` works too

**Comment by wasifhossain** [comment]
command shells that were open before you made the ruby version change won't have any effect, i.e. it will continue to use the previous version.

to make use of the new version, you can simply close that tab and open a new tab, which should work.

if that does not work, you can explicitly tell rvm which version to use: `rvm use 2.6.5`
