### ISSUE TITLE
how to define and reference nested (namespaced) serializer and controller

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#43]
I know that ``` rails g serializer user ``` will create a new path ``` app/serializers/user_serializer.rb ```, What shell instruction is for an ``` user_serializer ``` whose path is ``` app/serializers/api/v1/user_serializer.rb ```
**OR**
I will create that pathway manually?(I think I have to create it manually,but waiting for confirmation)

**Comment by sadmanahmed** [comment]
Update: I have gone through many links, the ams github link,rubygems.org but haven't get the answer I need.
More over , I have created ``` app/serializers/api/v1/user_serializer.rb ``` this manually but now the serialization file is not like active/called in the file (shouldnot the UserSerializer in Green word,that't what I am asking)
![ss](https://user-images.githubusercontent.com/19534210/79389654-64b7b280-7f90-11ea-96d6-13eaf30074b5.png)

**Comment by wasifhossain** [comment]
first, let's not rely on generators to do all the job for us. if you find anything hard to achieve with generators, just skip them and do it yourself

when you have namespaces (modules/classes) for the target class, you can do it in the following 2 ways:

**Option 1**:
```rb
module Api
  module V1
    class UserSerializer < ::ActiveModel::Serializer
    end
  end
end
```

Option 2:
```rb
class Api::V1::UserSerializer < ::ActiveModel::Serializer
end
```

[**Option 1** is preferred over option 2](https://guides.rubyonrails.org/autoloading_and_reloading_constants_classic_mode.html#nesting)

**Comment by wasifhossain** [comment]
let me know what issue are you facing with this

**Comment by wasifhossain** [comment]
are you using `gem 'jsonapi-rails'` by any chance?

**Comment by sadmanahmed** [comment]
Okay I have created the files manually and currently following option 2. But what about the color? is it okay(Shouldn't UserSerializer green?)?

> Update: I have gone through many links, the ams github link,rubygems.org but haven't get the answer I need.
> More over , I have created `app/serializers/api/v1/user_serializer.rb` this manually but now the serialization file is not like active/called in the file (shouldnot the UserSerializer in Green word,that't what I am asking)
> ![ss](https://user-images.githubusercontent.com/19534210/79389654-64b7b280-7f90-11ea-96d6-13eaf30074b5.png)

**Comment by sadmanahmed** [comment]
user_serializer.rb
```
class Api::V1::UserSerializer < ::ActiveModel::Serializer
  attributes(*User.attribute_names.map(&:to_sym))

  has_many :microposts, serializer: Api::V1::MicropostSerializer do
    include_data(false)
    link(:related) {api_v1_microposts_path(user_id: object.id)}
  end

  has_many :followers, serializer: Api::V1::UserSerializer do
    include_data(false)
    link(:related) {api_v1_user_followers_path(user_id: object.id)}
  end

  has_many :followings, key: :followings, serializer: Api::V1::UserSerializer do
    include_data(false)
    link(:related) {api_v1_user_followings_path(user_id: object.id)}
  end
end

```

**Comment by wasifhossain** [comment]
as I suggested earlier, please adopt **option 1** and after that, post your issues again

**Comment by sadmanahmed** [comment]
> are you using `gem 'jsonapi-rails'` by any chance?

No,but should I?

**Comment by wasifhossain** [comment]
> > are you using `gem 'jsonapi-rails'` by any chance?
> 
> No,but should I?

NO! just wondering where did you get `render jsonapi:` syntax

**Comment by sadmanahmed** [comment]
is the base_controller.rb is right now?
```
module Api
  module V1

    class BaseController < ActionController::Api

    rescue_from ActiveRecord::RecordNotFound, with: :not_found

      def not_found
        return api_error(status: 404, errors: 'Not found')
      end
    end
  end
end

```
Previos option 2 one was it
```
class Api::V1::BaseController < ActionController::API
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def not_found
    return api_error(status: 404, errors: 'Not found')
  end 
end
```

**Comment by sadmanahmed** [comment]
> > > are you using `gem 'jsonapi-rails'` by any chance?
> > 
> > 
> > No,but should I?
> 
> NO! just wondering where did you get `render jsonapi:` syntax

Just following the codes actually..

**Comment by wasifhossain** [comment]
pls update the user_serializer too using option 1 (nested namespace) syntax and share the file again

**Comment by sadmanahmed** [comment]
I am sharing this first time just for be sure, this is the users_controller.rb
from option 2
```
class Api::V1::UsersController < Api::V1::BaseController
  def show
    user = User.find(params[:id])

    render jsonapi: user, serializer: Api::V1::UserSerializer
  end
end
```
to option 1
```
module Api
  module V1
    class UsersController < BaseController
      def show
        user = User.find(params[:id])

        render jsonapi: user, serializer: Api::V1::UserSerializer
      end
    end
  end
end


```

**Comment by sadmanahmed** [comment]
but what will be the new substitute for  **Api::V1::UserSerializer**  ,is it ** UserSerializer**

**Comment by sadmanahmed** [comment]
https://github.com/ormprog/rails_ama/issues/43#issuecomment-614825468

Is the user_serializer.rb is in right format?
```
module Api
  module V1

    class UserSerializer < ::ActiveModel::Serializer
      attributes(*User.attribute_names.map(&:to_sym))

      has_many :microposts, serializer: MicropostSerializer do
        include_data(false)
        link(:related) {api_v1_microposts_path(user_id: object.id)}
      end

      has_many :followers, serializer: UserSerializer do
        include_data(false)
        link(:related) {api_v1_user_followers_path(user_id: object.id)}
      end

      has_many :followings, key: :followings, serializer: UserSerializer do
        include_data(false)
        link(:related) {api_v1_user_followings_path(user_id: object.id)}
      end
    end
  end
end

```

**Comment by sadmanahmed** [comment]
are the codes format right or I have to modify them?

**Comment by wasifhossain** [comment]
> I am sharing this first time just for be sure, this is the users_controller.rb
> from option 2
> 
> ```
> class Api::V1::UsersController < Api::V1::BaseController
>   def show
>     user = User.find(params[:id])
> 
>     render jsonapi: user, serializer: Api::V1::UserSerializer
>   end
> end
> ```
> 
> to option 1
> 
> ```
> module Api
>   module V1
>     class UsersController < BaseController
>       def show
>         user = User.find(params[:id])
> 
>         render jsonapi: user, serializer: Api::V1::UserSerializer
>       end
>     end
>   end
> end
> ```

as the user_serializer is now under the same nesting, you don't have to provide the serializer option in render explicitly. so the following should be fine
```rb
render jsonapi: user
```

**Comment by sadmanahmed** [comment]
> [#43 (comment)](https://github.com/ormprog/rails_ama/issues/43#issuecomment-614825468)
> 
> Is the user_serializer.rb is in right format?
> 
> ```
> module Api
>   module V1
> 
>     class UserSerializer < ::ActiveModel::Serializer
>       attributes(*User.attribute_names.map(&:to_sym))
> 
>       has_many :microposts, serializer: MicropostSerializer do
>         include_data(false)
>         link(:related) {api_v1_microposts_path(user_id: object.id)}
>       end
> 
>       has_many :followers, serializer: UserSerializer do
>         include_data(false)
>         link(:related) {api_v1_user_followers_path(user_id: object.id)}
>       end
> 
>       has_many :followings, key: :followings, serializer: UserSerializer do
>         include_data(false)
>         link(:related) {api_v1_user_followings_path(user_id: object.id)}
>       end
>     end
>   end
> end
> ```

Can you see this also..

**Comment by wasifhossain** [comment]
> [#43 (comment)](https://github.com/ormprog/rails_ama/issues/43#issuecomment-614825468)
> 
> Is the user_serializer.rb is in right format?
> 
> ```
> module Api
>   module V1
> 
>     class UserSerializer < ::ActiveModel::Serializer
>       attributes(*User.attribute_names.map(&:to_sym))
> 
>       has_many :microposts, serializer: MicropostSerializer do
>         include_data(false)
>         link(:related) {api_v1_microposts_path(user_id: object.id)}
>       end
> 
>       has_many :followers, serializer: UserSerializer do
>         include_data(false)
>         link(:related) {api_v1_user_followers_path(user_id: object.id)}
>       end
> 
>       has_many :followings, key: :followings, serializer: UserSerializer do
>         include_data(false)
>         link(:related) {api_v1_user_followings_path(user_id: object.id)}
>       end
>     end
>   end
> end
> ```

you can get rid of the serializer options from here too, as both the serializer classes are under same scope. so this should work
```rb
has_many :followings, key: :followings do
  include_data(false)
  link(:related) {api_v1_user_followings_path(user_id: object.id)}
end
```
