### ISSUE TITLE
How validation works in ActiveRecord when 'save' method is called

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#49]
**1**
I have added this code part in the user.rb but I didn't understand the methods.
```
.
.
 before_validation :ensure_token
.
.
private
.
.
  def ensure_token
    self.token = generate_hex(:token) unless token.present?
  end

  def generate_hex(column)
    loop do
      hex = SecureRandom.hex
      break hex unless self.class.where(column => hex).any?
    end
  end
.
.
```
**2**
also created a token column in users and add this bunch of code there
```
class AddTokenToUsers < ActiveRecord::Migration[5.0]
  def up
    add_column :users, :token, :string

    User.find_each{|user| user.save!}

    change_column_null :users, :token, false
  end

  def down
    remove_column :users, :token, :string
  end
end
```

**3**
I faced an error . At first I have created **2** then when I write **rails db:migrate** an error showes
```
.
.
PG::NotNullViolation: ERROR:  column "token" contains null values
.
.
```
But after I added the codes like **1** the migration runs well

**Comment by wasifhossain** [comment]
i am finding it difficult to get your issue. let me reorganize the flow and validate with you if i got it right

**Comment by wasifhossain** [comment]
Rephrasing the OP:

```rb
class AddTokenToUsers < ActiveRecord::Migration[5.0]
  def up
    add_column :users, :token, :string

    User.find_each{|user| user.save!}

    change_column_null :users, :token, false
  end

  def down
    remove_column :users, :token, :string
  end
end
```
running this migration got this error
```
PG::NotNullViolation: ERROR:  column "token" contains null values
```

But after adding this in the `User` model solved the error
```rb
.
.
 before_validation :ensure_token
.
.
private
.
.
  def ensure_token
    self.token = generate_hex(:token) unless token.present?
  end

  def generate_hex(column)
    loop do
      hex = SecureRandom.hex
      break hex unless self.class.where(column => hex).any?
    end
  end
.
.
```

Please confirm the case if I got it right

**Comment by wasifhossain** [comment]
first, you should add `null: false` and `default: ''` in the same statement while adding the new column in the migration file like this
```rb
class AddTokenToUsers < ActiveRecord::Migration[5.0]
  def up
    add_column :users, :token, :string, null: false, default: ''

    User.find_each{|user| user.save!}
  end

  def down
    remove_column :users, :token, :string
  end
end
```

and add a validation in the `User` model to make sure the `token` is present while adding a new user (should NOT be `nil` or an empty string):
```rb
# app/models/user.rb

validates :token, presence: true
```

**Comment by wasifhossain** [comment]
Now let's try to have an idea why adding the latest code helped you resolve the validation error.

Consider the [ActiveRecord::Base#save](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-save) call for a new record. Once the method is called, several other methods and callbacks are invoked in the following sequence:

    (-) save

    (-) valid

    (1) before_validation

    (-) validate

    (2) after_validation

    (3) before_save

    (4) before_create

    (-) create

    (5) after_create

    (6) after_save

    (7) after_commit

Here, `(-)` are method calls, while the numbered items are activerecord callbacks.

the validations that you write in an activerecord model are called during the `(-) validate` step.

In your code above, `ensure_token` method gets called during `before_validation` callback, which fills in an empty `token` with a random string, thus making it valid according to the validation that you might have already defined, i.e. `validates :token, presence: true`

In the next step, when `validate` is called, it will find the token present and eventually valid (if all other validations pass)

**Comment by sadmanahmed** [comment]
> Rephrasing the OP:
> 
> ```ruby
> class AddTokenToUsers < ActiveRecord::Migration[5.0]
>   def up
>     add_column :users, :token, :string
> 
>     User.find_each{|user| user.save!}
> 
>     change_column_null :users, :token, false
>   end
> 
>   def down
>     remove_column :users, :token, :string
>   end
> end
> ```
> 
> running this migration got this error
> 
> ```
> PG::NotNullViolation: ERROR:  column "token" contains null values
> ```
> 
> But after adding this in the `User` model solved the error
> 
> ```ruby
> .
> .
>  before_validation :ensure_token
> .
> .
> private
> .
> .
>   def ensure_token
>     self.token = generate_hex(:token) unless token.present?
>   end
> 
>   def generate_hex(column)
>     loop do
>       hex = SecureRandom.hex
>       break hex unless self.class.where(column => hex).any?
>     end
>   end
> .
> .
> ```
> 
> Please confirm the case if I got it right

Yes

**Comment by wasifhossain** [comment]
from the `generate_hex` method, it generates a random string and checks if its not present in any column in the table, i.e. if the generated string is unique.

in that sense, I think you should also add a **unique index on the `token` column** in the migration like this:
```rb
class AddTokenToUsers < ActiveRecord::Migration[5.0]
  def change # in place of `up`
    change_table :users, bulk: true do |t|
      t.column :token, :string, null: false, default: ''
      t.index :token, unique: true
    end

    up_only do # the block will only run when migrating UP
      User.find_each { |user| user.save! }
    end
  end
end
```
and extend the validation on the `token` column in the model
```rb
validates :token, presence: true, uniqueness: true
```

**Comment by wasifhossain** [comment]
as a refactoring step, `if` reads easier than `unless`. so if it's possible, we should use `if` in place of `unless`

e.g. 
- `unless token.present?` can be written as 
```rb
if token.blank?
```
- `unless self.class.where(column => hex).any?` can be written as 
```rb
if self.class.where(column => hex).none?
```

**Comment by sadmanahmed** [comment]
Bit Complex, need practice to learn it properly

> Now let's try to have an idea why adding the latest code helped you resolve the validation error.
> 
> Consider the [ActiveRecord::Base#save](https://api.rubyonrails.org/classes/ActiveRecord/Persistence.html#method-i-save) call for a new record. Once the method is called, several other methods and callbacks are invoked in the following sequence:
> 
> ```
> (-) save
> 
> (-) valid
> 
> (1) before_validation
> 
> (-) validate
> 
> (2) after_validation
> 
> (3) before_save
> 
> (4) before_create
> 
> (-) create
> 
> (5) after_create
> 
> (6) after_save
> 
> (7) after_commit
> ```
> 
> Here, `(-)` are method calls, while the numbered items are activerecord callbacks.
> 
> the validations that you write in an activerecord model are called during the `(-) validate` step.
> 
> In your code above, `ensure_token` method gets called during `before_validation` callback, which fills in an empty `token` with a random string, thus making it valid according to the validation that you might have already defined, i.e. `validates :token, presence: true`
> 
> In the next step, when `validate` is called, it will find the token present and eventually valid (if all other validations pass)

**Comment by sadmanahmed** [comment]
Okay I will try this....
> as a refactoring step, `if` reads easier than `unless`. so if it's possible, we should use `if` in place of `unless`
> 
> e.g.
> 
> * `unless token.present?` can be written as
> 
> ```ruby
> if token.blank?
> ```
> 
> * `unless self.class.where(column => hex).any?` can be written as
> 
> ```ruby
> if self.class.where(column => hex).none?
> ```
