### ISSUE TITLE
JSON output error

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#51]
I need to know what actually this means(the instruction in bold ), is it a get request or post request
(I might get the above result after I create the sessions_controller.rb and session_serializer.rb in #50 )
**The client probably needs only user's id, email and token but it's good to return some more data for better optimization. We might save us from an extra request to the users endpoint :)**
```
{
  "data": {
    "id": "1",
    "type": "session",
    "attributes": {
      "email": "example@railstutorial.org",
      "token": "f42f5ccee3689209e7ca8e4f9bd830e2",
      "user-id": 1
    },
    "relationships": {
      "user": {
        "data": {
          "id": "1",
          "type": "users"
        },
        "links": {
          "self": "/api/v1/users/1",
          "related": "/api/v1/users/1"
        }
      }
    }
  },
  "included": [
    {
      "id": "1",
      "type": "users",
      "attributes": {
        "name": "Example User",
        "email": "example@railstutorial.org",
        "created-at": "2016-11-05T10:15:26Z",
        "updated-at": "2016-11-19T21:30:10Z",
        "password-digest": "$2a$10$or7HFYm/H07/uE79wDae3uXMmHOX3BvRKdgedPJ1SPceiMA40V25O",
        "remember-digest": null,
        "admin": true,
        "activation-digest": "$2a$10$X5IeDtGZPuZQEVQ.ZiUP4eUzfw9M9Pag/nR.0ONiXwAAp3w98iAuC",
        "activated": true,
        "activated-at": "2016-11-05T10:15:26.300Z",
        "reset-digest": null,
        "reset-sent-at": null,
        "token": "f42f5ccee3689209e7ca8e4f9bd830e2",
        "microposts-count": 99,
        "followers-count": 37,
        "followings-count": 48,
        "following-state": false,
        "follower-state": false
      },
      "relationships": {
        "microposts": {
          "links": {
            "related": "/api/v1/microposts?user_id=1"
          }
        },
        "followers": {
          "links": {
            "related": "/api/v1/users/1/followers"
          }
        },
        "followings": {
          "links": {
            "related": "/api/v1/users/1/followings"
          }
        }
      }
    }
  ]
}
```

**Comment by sadmanahmed** [comment]
Is the json output is a result of any get request(e.g. localhost:3000/api/v1/users/1 but the outcome of this data type is 'user' here the expected data is 'session')

**Comment by wasifhossain** [comment]
most probably a GET request.

and the above json seems to be a session object; not a user object

**Comment by sadmanahmed** [comment]
if this is a json output, what might be the get request?

**Comment by wasifhossain** [comment]
you can craft a json in any way as you wish. it does not matter if its a response from a GET/POST request. what really matters is what exact structure would you like to have and then work on the serializer that would give you the desired output

**Comment by sadmanahmed** [comment]
Sorry ,Actually finding it difficult to answer many questions. Trying to short the questions..

**Comment by sadmanahmed** [comment]
But what can be the Get request for a session object like this?

**Comment by wasifhossain** [comment]
from #50, i thought its the output of a POST request; `sessions#create` to be specific

**Comment by sadmanahmed** [comment]
Have not initialized any create method in the users_controller.rb till now,but I will(the api one)

**Comment by sadmanahmed** [comment]
I have initialized create method in the sessions_controller.rb , How can I use it in postman?(as a post request)

**Comment by wasifhossain** [comment]
> I have initialized create method in the sessions_controller.rb , How can I use it in postman?(as a post request)

this is something different than the OP, I assume. could you take some time to edit the OP in that case and make your intents clear what you are trying to achieve

e.g. i would have created a new issue with this specific question and close this one (or do you have clear reason to keep it open)

**Comment by sadmanahmed** [comment]
Actually I want that json output https://github.com/ormprog/rails_ama/issues/51#issue-602512841 ,Wondering how can i get it,that's what all my query for now

**Comment by wasifhossain** [comment]
now it became clear that #50 contains all the info to answer this, like
- how does the sessions controller look like
- session serializer
- expected json output

then i think we can close this and go back to there to have an answer
