### ISSUE TITLE
NoMethodError 

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#52]
**1**
After sending a get request I found this error
```
Started GET "/api/v1/users/1" for ::1 at 2020-04-20 00:08:06 +0600
Processing by Api::V1::UsersController#show as */*
  Parameters: {"id"=>"1"}
  User Load (0.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/api/v1/users_controller.rb:10:in `show'
Completed 500 Internal Server Error in 245ms (ActiveRecord: 0.8ms | Allocations: 64641)


  
NoMethodError (undefined method `authorize_with_permissions' for #<Api::V1::UsersController:0x000055dd5fcf16c8>):
  
app/controllers/api/v1/users_controller.rb:10:in `show'

```
I have this method  **authorize_with_permissions** in the **show**

So I think I have to create the **authorize_with_permissions** method,right? but Where should I?

**2**
So I was digging down the Root of this. 
I installed this gem **flexible-permissions** https://github.com/vasilakisfil/flexible-permissions
and it is co related with gem **pundit**
So there I found the same code(I write in the **Show**) with same  **authorize_with_permissions** method. This method leads me to this code
https://github.com/vasilakisfil/flexible-permissions/blob/e0e6cb36f2513b3b5e55fc9d68a78ec02d9b0197/lib/flexible_permissions/pundit.rb#L2
```
module AuthorizeWithReturn
  def authorize_with_permissions(record, query=nil)
    query ||= params[:action].to_s + '?'
    @_pundit_policy_authorized = true

    policy = policy(record)
    policy.public_send(query)
  end

  def included
    super
    hide_action :authorize
  end
end

module Pundit
  prepend AuthorizeWithReturn
end
```

So , what should I do? Create a pundit.rb file in the lib/flexible_permissions directory ? or create the
**authorize_with_permissions** method in api/v1/user_controller.rb

**Comment by sadmanahmed** [comment]
I have manually  Create a pundit.rb file in the lib/flexible_permissions directory and lead to the issue no #53

**Comment by wasifhossain** [comment]
`authorize_with_permissions` is provided by the gem. so you just have to call it
