### ISSUE TITLE
How to set Authorization header in HTTP Token authentication

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#53]
```
def show
        auth_user = authorize_with_permissions(User.find(params[:id]))

        render json: auth_user.record,
        fields: {user: auth_user.fields},
        adapter: :json_api


         # user = User.find(params[:id])
         # render json: user, adapter: :json_api

      end
```
the 1st portion has the outcome of this. Is this needs some authorization to show the details? as in the commented 2 lines has a more detailed json outcome(in the next comment)
```
{
    "data": {
        "id": "1",
        "type": "users",
        "attributes": {
            "name": "Abir",
            "created-at": "2020-03-26T17:16:38.166Z"
        },
        "relationships": {
            "microposts": {
                "links": {
                    "related": "/api/v1/microposts?user_id=1"
                }
            },
            "followers": {
                "links": {
                    "related": "/api/v1/users/1/followers"
                }
            }
        }
    }
}
```

**Comment by sadmanahmed** [comment]
when this 2 line is active and rest the show method is comment out 
```
user = User.find(params[:id])
render json: user, adapter: :json_api

```
json outcome
```
{
    "data": {
        "id": "1",
        "type": "users",
        "attributes": {
            "name": "Abir",
            "email": "abirssc7@gmail.com",
            "created-at": "2020-03-26T17:16:38.166Z",
            "updated-at": "2020-04-17T21:41:31.696Z",
            "password-digest": "$2a$12$XmlVaxjArDUCFeOWjOGYWORCEcfCW3.GBMarZrsLCh1PdXeNRKHS2",
            "remember-digest": null,
            "admin": true,
            "activation-digest": "$2a$12$/Y3zRUi1gr9GXSCBKUw9Oet5o8z6T6.tL5e09g21TKSodQkxe.xoa",
            "activated": true,
            "activated-at": "2020-03-26T17:16:37.811Z",
            "reset-digest": null,
            "reset-sent-at": null,
            "token": "5cb13288cd629e9cdf72c167f3a4d750"
        },
        "relationships": {
            "microposts": {
                "links": {
                    "related": "/api/v1/microposts?user_id=1"
                }
            },
            "followers": {
                "links": {
                    "related": "/api/v1/users/1/followers"
                }
            },
            "followings": {
                "links": {
                    "related": "/api/v1/users/1/followings"
                }
            }
        }
    }
}
```

**Comment by sadmanahmed** [comment]
I want to add that **IT SEEMS LIKE** in the 1st portioned code(auth_user) it gives output as a guest user, and in the 2nd portion(user) it gives like a regular user(Reference:Granular Permission )

**Comment by wasifhossain** [comment]
`authorize_with_permissions` scopes the result for the current user

**Comment by sadmanahmed** [comment]
What is the usage of the Authorization column in the postman? is it related with this issue? I tried with the basic auth, but same result came up

**Comment by wasifhossain** [comment]
to answer that, first I have to know how you have designed the parent controller to send in the authorization credentials

**Comment by wasifhossain** [comment]
if I assume it right, you are still following https://github.com/vasilakisfil/rails5_api_tutorial

in that case, its done by something like this
> ActionController::HttpAuthentication::Token parses Authorization header which holds the token. Actually, an Authorization header looks like that:
>
> Authorization: Token email=myemail@email.com, token="f42f5ccee3689209e7ca8e4f9bd830e2"

**Comment by wasifhossain** [comment]
you can set the Authorization header manually in Postman like this:

![image](https://user-images.githubusercontent.com/1168927/80098336-81ef1100-858e-11ea-97c7-7b5d3b5d4f7f.png)

So if you set the token in the Authorization header this way:
```
Authorization: Token token="abdjdfdfjkkjkkdjfkjdkjfk", email="a@b.c"
```

Here you can use either `Token` or `Bearer`, so the following should work too. 
```
Authorization: Bearer token="abdjdfdfjkkjkkdjfkjdkjfk", email="a@b.c"
```
the order of token is important here. the first key=value pair would be parsed as token.

we can now parse it by calling [`token_and_options`](https://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Token.html#method-i-token_and_options): 
```rb
token, options = ActionController::HttpAuthentication::Token.token_and_options(request)
```
here `token` will be `abdjdfdfjkkjkkdjfkjdkjfk` and `options` will be a hash like `{ email: "a@b.c" }`

you can also find out how to set the value for the `Authorization` header by calling [`encode_credentials`](https://api.rubyonrails.org/classes/ActionController/HttpAuthentication/Token.html#method-i-encode_credentials)
```rb
ActionController::HttpAuthentication::Token.encode_credentials('hello_world', email: 'a@b.c')
# => "Token token=\"hello_world\", email=\"a@b.c\""
```

**Comment by sadmanahmed** [comment]
Okay understood this part. 
but for this Authorization : Token email=abirssc7@gmail.com, token="5cb13288cd629e9cdf72c167f3a4d750" (from https://github.com/ormprog/rails_ama/issues/53#issuecomment-616218864) the result is same . Is this okay?
```
{
    "data": {
        "id": "1",
        "type": "users",
        "attributes": {
            "name": "Abir",
            "created-at": "2020-03-26T17:16:38.166Z"
        },
        "relationships": {
            "microposts": {
                "links": {
                    "related": "/api/v1/microposts?user_id=1"
                }
            },
            "followers": {
                "links": {
                    "related": "/api/v1/users/1/followers"
                }
            }
        }
    }
}
```

**Comment by wasifhossain** [comment]
what do you mean by okay?

**Comment by sadmanahmed** [comment]
Actually the Authorization: Token email = anything, token = "anything", is giving same result. Is this normal? even without Authorization header, the result (Json) one is same

**Comment by wasifhossain** [comment]
perhaps. if you don't see any error, then it might be ok

**Comment by sadmanahmed** [comment]
Okay we are closing this issue but still I am confused about the **WORKING RATIO** of the authentication. Maybe some features still missing as I have not copied all the code, rather I am typing them by hand to understand them(As much as I can) and going through the git

**Comment by sadmanahmed** [comment]
https://github.com/ormprog/rails_ama/issues/53#issuecomment-616235655
There is a small correction .(no " " in the email portion)
```
Authorization: Token token="abdjdfdfjkkjkkdjfkjdkjfk", email= a@b.c
```
just get the result

**Comment by wasifhossain** [comment]
what do you get if the email value is quoted

**Comment by sadmanahmed** [comment]
ah , now it is working fine for both case, maybe at the first time server did not respond properly.
