### ISSUE TITLE
How the test user.yml is working at the last part of the code?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#6]
![ss](https://user-images.githubusercontent.com/19534210/70745016-2c3b6a00-1d4d-11ea-9a30-5eda9c140a10.png)

**Comment by wasifhossain** [comment]
its a simple ruby loop, where it will iterate 30 times and yield the current number to the block in each iteration starting from 0 and ending in 29.

rails supports ruby code inside yaml enclosed with `<%` and `%>`.

**Comment by wasifhossain** [comment]
ruby code that is NOT meant for output is started with `<%`, while the code that is expected to be output starts with `<%=`
