### ISSUE TITLE
how to setup pgadmin for a current database

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#61]
I need to see my db in this pgadmin .
![ss](https://user-images.githubusercontent.com/19534210/80288096-6edb6d00-8757-11ea-9bf5-30268afccc72.png)

**Comment by sadmanahmed** [comment]
dbname is **sample_app_development**
I can remember user name as **abir** from #59

**Comment by wasifhossain** [comment]
could you expand `Servers` on the left pane and share ss

**Comment by sadmanahmed** [comment]
![ss](https://user-images.githubusercontent.com/19534210/80288155-d72a4e80-8757-11ea-97fd-1153fda5f572.png)

**Comment by wasifhossain** [comment]
you can follow this guide: http://yallalabs.com/linux/how-to-connect-to-a-postgresql-database-using-pgadmin4/
