### ISSUE TITLE
Pagination Error 

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#65]
![ss](https://user-images.githubusercontent.com/19534210/80318919-4626a680-882f-11ea-8933-f3a2e9ff4e34.png)
**Page 1**
url : http://localhost:3000/help

**Page 2**
![ss](https://user-images.githubusercontent.com/19534210/80319003-e11f8080-882f-11ea-85bf-1b5251ceb033.png)

url : http://localhost:3000/?page=2

The page is not staying on the all event (page 1)

**Comment by wasifhossain** [comment]
do you mean 

http://localhost:3000/help?page=2

OR

http://localhost:3000/?page=2

**Comment by sadmanahmed** [comment]
it should be like this http://localhost:3000/help?page=2

**Comment by wasifhossain** [comment]
```
rails routes | grep -i help
```

**Comment by sadmanahmed** [comment]
help.html.erb
```
<% provide(:title, "Help") %>
<div class="center jumbotron">
<% if logged_in? %>
  <div class="row">

    <div class="col-md-8">
      <h3>Event Board</h3>
      <%= render 'shared/feed1' %>
    </div>

  </div>
<% else %>
<h1>Help</h1>


<p>
  It is a basic site. Log in for more features.
</p>
<% end %>

```

_feed1.html.erb
```
<% if @feed1_items.any? %>
  <ol class="microposts">
    <%= render @feed1_items %>
  </ol>
  <%= will_paginate @feed1_items,
                    params: { controller: :static_pages, action: :home } %>
<% end %>

```
feed1 method
```
def feed1
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    #Micropost.where("user_id IN (#{following_ids})
    #                 OR user_id = :user_id", user_id: id)
    Micropost.all #will bring all the posts
  end
```

**Comment by sadmanahmed** [comment]
I think we have to make some changes here : **<%= will_paginate @feed1_items,
                    params: { controller: :static_pages, action: :home } %>**

**Comment by sadmanahmed** [comment]
SOLVED

**Comment by sadmanahmed** [comment]
I just changed home to help **<%= will_paginate @feed1_items,
params: { controller: :static_pages, action: :help } %>**

**Comment by sadmanahmed** [comment]
![ss](https://user-images.githubusercontent.com/19534210/80323079-f5bd4200-884a-11ea-9bc0-4eb496024736.png)
the url is perfect now
