### ISSUE TITLE
How the other API users can access my api?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#68]
I have provided my API to my partners and then How actually then can use the API ?Actaully what is the login process here? The session one? 

how the key from active_storage_blobs and token form users playing role here?

**Comment by wasifhossain** [comment]
YES! `POST /api/v1/sessions` is working as the login endpoint for your app

managing keys would be a difficult process if you hand it over. I would suggest that you control the app deployment and make sure the app runs smooth on heroku. then tell them to make the api calls to your app

**Comment by sadmanahmed** [comment]
When in the postman we call the session , we get the token here.
then we manually authorized the other call for users/microposts and others... in the postman app..

But how it will work for a mobile app? is it will an automated process OR the mobile developer have to fetch the token by hand written code ?

**Comment by wasifhossain** [comment]
by implementing the api client for mobile, which would perform the exact thing that you did using Postman :)

**Comment by sadmanahmed** [comment]
okay , we will talk about it tomorrow then... after implementing the api in the mobile

**Comment by sadmanahmed** [comment]
this ss from the flutter site and this error message is showing
**My friend says:** 
`Username and password is working but it sends wrong data. Any idea why?
Because of wrong data,it is showing error message. So,data is going but why it is sending wrong data i am not sure.`
![IMG_20200429_233346](https://user-images.githubusercontent.com/19534210/80633116-0d2e4200-8a7a-11ea-9686-c2ecf8f85aab.jpg)

**Comment by wasifhossain** [comment]
when the api client receives 4xx status, it indicates that the api client itself might have made any mistake while making the api call to the server

here the api client is the **flutter app** that your partner is working on.

can you ask him to check if he is making the request properly. he can use Insomnia (https://insomnia.rest/) to make a test api call and see if he is able to do that successfully

**Comment by sadmanahmed** [comment]
any probable solution ?

**Comment by sadmanahmed** [comment]
okay.... asking him..

**Comment by wasifhossain** [comment]
feel free to reopen if you find it best
