### ISSUE TITLE
Want to add a destroy action in session controller api

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#73]
```
# frozen_string_literal: true

module Api
  module V1
    class SessionsController < BaseController
      before_action :load_resource
      skip_before_action :authenticate_user!, only: [:create]

      def create
        if @user
          render(
            json: @user, serializer: SessionSerializer,
            status: :created, include: [:user], scope: @user,
            adapter: :json_api
          )
        else
          api_error(status: 401, errors: 'Wrong password or username')
        end
      end

      def show
        authorize(@user)

        render(
          json: @user, serializer: SessionSerializer,
          status: :ok, include: [:user], fields: {
            user: UserPolicy::Regular.new(@user).fields,
            adapter: :json_api
          }
        )
      end

      private

      def create_params
        normalized_params.permit(:email, :password)
      end

      def load_resource
        case params[:action].to_sym
        when :create
          @user = User.find_by(
            email: create_params[:email]
          )&.authenticate(create_params[:password])
        when :show
          @user = User.find(params[:id])
        end
      end

      def normalized_params
        ActionController::Parameters.new(
          ActiveModelSerializers::Deserialization.jsonapi_parse(params)
        )
      end
    end
  end
end

```

destroy action in the normal session_controller.rb
```
def destroy
    log_out if logged_in?
    redirect_to root_url
  end
```

```
# Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
```
```
def logged_in?
    !current_user.nil?
  end
```
**Is it something like this** 
```
def destroy
    authorize(@user)
    render render(
            json: @user, serializer: SessionSerializer,
            status: :destroyed, include: [:user], scope: @user,
            adapter: :json_api
          )

```

**Comment by wasifhossain** [comment]
seems to be. 

first `authenticate_user!` will make sure the request is accompanied with a valid user token.

next `authorize(@user)` will make sure that the current user is allowed to perform the action.

both of the above steps are already done; except that you have to modify the `load_resource` method for this action.

finally, the most important thing, you have to take the steps to **make the current token invalid** before returning a response, so that the current token can't be used anymore to make any requests

**Comment by sadmanahmed** [comment]
The updated sessions load resources will be like this then? but how can it destroy a session?
```
def load_resource
        case params[:action].to_sym
        when :create
          @user = User.find_by(
            email: create_params[:email]
          )&.authenticate(create_params[:password])
        when :show
          @user = User.find(params[:id])
        
        when :destroy
        @user = User.find(params[:id])
      end
      end
```

**Comment by wasifhossain** [comment]
`rails routes | grep -i session`

**Comment by wasifhossain** [comment]
lets see the top level controller from which all api controllers inherit from

**Comment by sadmanahmed** [comment]
```
sample_app git:(api) ✗ rails routes | grep -i session
                                login GET    /login(.:format)                                                                         sessions#new
                                      POST   /login(.:format)                                                                         sessions#create
                               logout DELETE /logout(.:format)                                                                        sessions#destroy
                      api_v1_sessions POST   /api/v1/sessions(.:format)                                                               api/v1/sessions#create
                       api_v1_session GET    /api/v1/sessions/:id(.:format)                                                           api/v1/sessions#show
```

**Comment by sadmanahmed** [comment]
seems like we have not defined destroy in the route

**Comment by sadmanahmed** [comment]
```
# api
  namespace :api do
    namespace :v1 do
      resources :sessions, only: %i[create show]
      resources :users, only: %i[index create show update destroy] do
        post :activate, on: :collection
        resources :followers, only: %i[index destroy]
        resources :followings, only: %i[index destroy] do
          post :create, on: :member
        end
        resource :feed, only: [:show]
      end
      resources :microposts, only: %i[index create show update destroy]
    end
  end
end

```

**Comment by sadmanahmed** [comment]
need to add destroy in the route (in the session section,right?) like
`  resources :sessions, only: %i[create show destroy] `

**Comment by sadmanahmed** [comment]
I think this should be the destroy action in the session api for logout
```
def destroy
    authorize(@user)
    @session.destroy!
render render(
            json: @user, serializer: SessionSerializer,
            status: :destroyed, include: [:user], scope: @user,
            adapter: :json_api
          )
```
but in the load resources I am confused with this... how is this?
```
when :destroy
        @session = log_out if logged_in?
```

**Comment by sadmanahmed** [comment]
but can't understand how to proceed..

**Comment by wasifhossain** [comment]
where does `@session` now come into existence in `@session.destroy!`? i don't see any usage of Session instance in api/v1/sessions yet

**Comment by sadmanahmed** [comment]
> where does `@session` now come into existence in `@session.destroy!`? i don't see any usage of Session instance in api/v1/sessions yet

Just an assumption , nothing else

**Comment by sadmanahmed** [comment]
> make the current token invalid

How to make this happen **make the current token invalid**

**Comment by wasifhossain** [comment]
if you change it, the previous one won't be valid anymore. as simple as this :)

**Comment by wasifhossain** [comment]
but you should also read this: https://rollout.io/blog/why-you-shouldnt-roll-your-own-authentication/

**Comment by sadmanahmed** [comment]
> if you change it, the previous one won't be valid anymore. as simple as this :)

then How can we add a signout option in the api? (Reading the link you provided)

**Comment by wasifhossain** [comment]
to be honest, **api authentication** is quite different than **human authentication** in their own challenges. e.g. **Devise** works for authenticating human requests, but not for api. you could use another gem for the purpose, known as **devise_token_auth**, which, as the name suggests, is based on devise.

as the above link suggested, you should integrate proven tools in your project to better deal with this security feature.

for simplicity in your current code, you could just generate a new token inside the `destroy` action in the same way how you are doing that while creating a new user (remember the `User#generate_token` method?). this will replace the existing token with a new one. so future api calls with the older token wouldn't be found in db anymore, thus preventing the api calls with older tokens. So they would need to sign in to Sessions#create and obtain the new token to use it for later api requests
