### ISSUE TITLE
String#index

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#74]
Can you elaborate it ? I know index gives the first position of the arguments inside the method.. But this seems like something complex/
```
2.6.5 :011 > "hello".index(/[aeiou]/, -3)
 => 4 
```

**Comment by wasifhossain** [comment]
the example matches the following pattern:
> str.index(regexp [, offset]) → integer or nil 

from the doc:
> If the second parameter is present (i.e. offset), it specifies the position in the string to **begin the search**.

```
                 h  e  l  l  o
                 ^  ^  ^  ^  ^
forward index:   0  1  2  3  4
backward index: -5 -4 -3 -2 -1
```
with offset -3, the method will start searching from the 1st `l` with index 2 and will match `o` with the `/[aeiou]/` pattern, which index is: **4**
