### ISSUE TITLE
how to setup ruby, rvm, editor, postgresql and connect to an existing github repository after completely new system setup?

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#75]
I am downloading the previous working file from GitHub. After unzipping, copy the file into a directory.

**https://guides.rubyonrails.org/getting_started.html** following this link instruction for further steps.

In the terminal, install **`ruby`** via `sudo apt-get install ruby-full` this command. 

Then check the `ruby` version 
it shows `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

**But in the previous working system was `ruby '2.6.3'`**

Install **`sqlite3`** via `sudo apt install sqlite3` this command.
Check the `sqlite3` version
It shows `3.22.0 2018-01-22 18:45:57`

Install **`nodejs`** via `sudo apt install nodejs`
its version check via `node --version` and it shows `v8.10.0`
Its require greater than `8.16.0` then I visit ****https://github.com/nodesource/distributions/blob/master/README.md****
this link and run those command
`curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -`
`sudo apt-get install -y nodejs`
and `apt-get install -y build-essential` 
After I checked `nodejs` version, it shows `v14.3.0`

Installing `yarn` via visiting **https://classic.yarnpkg.com/en/docs/install#debian-stable** link
run a few commands 
 `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -`
`echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list`
`sudo apt update && sudo apt install yarn`
then check the version, it shows `1.22.4`

To install rails, run `gem install rails`
But it shows an error message **`ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have to write permissions for the /var/lib/gems/2.5.0 directory.`**

What should I do in next?

**Comment by wasifhossain** [comment]
basically we install Ruby using a version manager like RVM. you can follow this to install Ruby

http://cheat.errtheblog.com/s/rvm

**Comment by wasifhossain** [comment]
please post further questions here if you have

**Comment by ansary14-zz** [comment]
I install `ruby` earlier. Am I needing to remove the earlier one?

**https://stackoverflow.com/questions/37720892/you-dont-have-write-permissions-for-the-var-lib-gems-2-3-0-directory**

Here says first I remove `ruby`, then install ruby via **`rbenv`**.

**Comment by ansary14-zz** [comment]
I uninstall `ruby` first by `sudo apt-get remove ruby` command

Then visit **`https://rvm.io/`** for **rvm install**

I pass 3 commands 
for install `GPG keys`
`gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`
for install `RVM`
`\curl -sSL https://get.rvm.io | bash -s stable` 
for install `RVM default in ruby and rails`
`\curl -sSL https://get.rvm.io | bash -s stable --rails`

Output like **`To start using RVM you need to run `source /home/ayub/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.`**

`source /home/ayub/.rvm/scripts/rvm` after passing this command,
check the ruby and rails version 
`ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]`
`Rails 6.0.3.1`

**Comment by ansary14-zz** [comment]
`Required ruby-2.6.3 is not installed.
To install do: 'rvm install "ruby-2.6.3"'`

It shows when I change directory to my previous working file directory. 
`cd alpha-blog-master`

What should I pass the command which suggested? or anything else

**Comment by ansary14-zz** [comment]
Inform you again that my previous working environment is `ruby -2.6.3`

@wasifhossain vai reply to me when you see.

**Comment by ansary14-zz** [comment]
I run above suggest command `rvm install ruby-2.6.3` now it does not show any error message.

I'm using Atom. Previously from the working directory run `atom .` this command for opening Atom.
But now it shows an error. 
here is ss 
![Screenshot from 2020-06-01 14-47-59](https://user-images.githubusercontent.com/33208962/83392485-fed79b00-a416-11ea-997c-628be66605d6.png)

**Comment by ansary14-zz** [comment]
I need suggestions to reconnect my previous working folder. Any documentation.

**Comment by ansary14-zz** [comment]
I am solving my atom issue. Which previously I describe.
By the following _instruction_ from this site
**https://flight-manual.atom.io/getting-started/sections/installing-atom/**

**Comment by ansary14-zz** [comment]
![Screenshot from 2020-06-02 19-24-53](https://user-images.githubusercontent.com/33208962/83525415-c3b49500-a506-11ea-9082-56e5d33ac1ca.png)

What I do next?

**Comment by wasifhossain** [comment]
> `Required ruby-2.6.3 is not installed. To install do: 'rvm install "ruby-2.6.3"'`
> 
> It shows when I change directory to my previous working file directory.
> `cd alpha-blog-master`
> 
> What should I pass the command which suggested? or anything else

as different ruby projects can use different versions of ruby, thats why we use RVM, which allows easier version management.

the following command will use ruby 2.6.3 for the current project and before that, it will install it first if missing
```
rvm use 2.6.3 --install
```

**Comment by wasifhossain** [comment]
let me know your latest issue that you are finding hard to solve yourself

**Comment by ansary14-zz** [comment]
It's done already. 

my latest issue is 
![Screenshot from 2020-06-02 19-24-53](https://user-images.githubusercontent.com/33208962/84282998-4919f400-ab5c-11ea-8f3c-439db4fa6e53.png)

What I do next?
How I connect my GitHub account?

**Comment by wasifhossain** [comment]
you can push/pull commits to/from github using CLI
```
git push origin <branch-name>
```
or
```
git pull origin <branch-name>
```

**Comment by wasifhossain** [comment]
can you share the output of `git remote -v`

**Comment by ansary14-zz** [comment]
I faced a problem with the atom terminal.
here is ss 
![Screenshot from 2020-06-10 21-03-09](https://user-images.githubusercontent.com/33208962/84284359-e32e6c00-ab5d-11ea-9431-d047a108a0c4.png)

It shows nothing, and it doesn't take any input.

**Comment by wasifhossain** [comment]
I don't use atom, so can't help with that.

it would be better for you to use a terminal to execute the commands instead of relying on editor-powered shells

**Comment by ansary14-zz** [comment]
Okay. 

As you say to pass the command `git remote -v`
I passed the command in my terminal. It shows nothing!
![Screenshot from 2020-06-10 21-12-19](https://user-images.githubusercontent.com/33208962/84285266-14f40280-ab5f-11ea-9334-b694533174fc.png)

**Comment by ansary14-zz** [comment]
What do I need to do
![Screenshot from 2020-06-10 21-21-00](https://user-images.githubusercontent.com/33208962/84286501-95673300-ab60-11ea-9748-f36fb15c1b09.png)
?

**Comment by wasifhossain** [comment]
I see. so `git status` reports you have no commits created yet. 

is it really the case, or do you already have a repo on github. if yes, you should clone the repo into your machine and continue from there instead of starting it all over

**Comment by ansary14-zz** [comment]
Yes, I have GitHub repo. 
How to clone the repo in my machine?

**Comment by wasifhossain** [comment]
just visit the repo homepage on github and find out the url under the green "clone or download" button. then `cd` to a suitable directory on your machine, open a terminal from that directory and run
```
git clone <url-that-you-copied>
```
once its done, you can `cd` to the project directory and continue your work

**Comment by ansary14-zz** [comment]
Yes, It's done. 

Thank you, vaia.

**Comment by ansary14-zz** [comment]
I face some problem with rails.
Let's have a look into the screenshot
![Screenshot from 2020-06-11 12-00-19](https://user-images.githubusercontent.com/33208962/84350566-63df7d80-abdb-11ea-9ffa-90f446e23dbf.png)

**Comment by ansary14-zz** [comment]
I run the command `bundle install`

It shows an error.
error message: 
**An error occurred while installing pg (1.2.2), and Bundler cannot
continue.
Make sure that `gem install pg -v '1.2.2' --source 'https://rubygems.org/'`
succeeds before bundling.
**

**Comment by ansary14-zz** [comment]
After passing the command `gem install pg -v '1.2.2' --source 'https://rubygems.org/'`

it shows
**ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.
**

**Comment by wasifhossain** [comment]
one thing to remember is that ruby/rails versions should be considered **project-wise** instead of global. so only care about the version of these what you find inside a ruby/rails project.

back to the issue, `rails -v` inside the project (alpha-blog) is complaining of `rails 6.0.2.1` to be missing from the ruby 2.6.3 gemset. the solution would be to install the missing rails version by running `bundle install`, which you have already done, that is now ended up with `pg` installation error.

the current issue that `pg` is failing might have several reasons. we need to fix this first in order to install that rails version. 

could you please share the whole error message that you get after running `bundle install`. post the output in text format by wrapping with 3 backticks in the beginning and end in their own lines. if you are confused about which part of the whole output should be considered as error message, then just paste the whole output

**Comment by ansary14-zz** [comment]
```
ayub@ayub:~/railsproject/alpha-blog$ bundle install
...
Fetching pg 1.2.2
Installing pg 1.2.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/ayub/.rvm/gems/ruby-2.6.3/gems/pg-1.2.2/ext
/home/ayub/.rvm/rubies/ruby-2.6.3/bin/ruby -I /home/ayub/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0 -r ./siteconf20200611-1900-3kpv0u.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/ayub/.rvm/rubies/ruby-2.6.3/bin/$(RUBY_BASE_NAME)
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ayub/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/pg-1.2.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ayub/.rvm/gems/ruby-2.6.3/gems/pg-1.2.2 for inspection.
Results logged to /home/ayub/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/2.6.0/pg-1.2.2/gem_make.out

An error occurred while installing pg (1.2.2), and Bundler cannot continue.
Make sure that `gem install pg -v '1.2.2' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  pg
```

**Comment by wasifhossain** [comment]
looks like a header file is missing, which is provided by `libpq-dev`. lets install this app first and retry bundle install
```
sudo apt install libpq-dev
```

the answer is detailed on StackOverflow too: https://stackoverflow.com/questions/6040583/cant-find-the-libpq-fe-h-header-when-trying-to-install-pg-gem
