### ISSUE TITLE
How can recover previously input data into database

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#76]
After cloning the GitHub repo.
run `rails db:migrate`

After migration successfully, I checked my previous table data by run `Article.all`
It shows 
```
(0.6ms)  SELECT sqlite_version(*)
  Article Load (0.3ms)  SELECT "articles".* FROM "articles" LIMIT ?  [["LIMIT", 11]]
 => #<ActiveRecord::Relation []> 
```

Previously I have created 2 tables, Articles and Users table. 
I put some entry into the database.
But Showing that there are no users and articles.

**Comment by ansary14-zz** [comment]
```
Correct me if I am wrong :
git pull
rails db:migrate
git push (just to check everything is updated or not)
Post this one the issues. Or you can check issue no 31
https://github.com/ormprog/rails_ama/issues/31
```
As abir via says, I checked all the command. It shows **everything is up-to-date**

**Comment by ansary14-zz** [comment]
After Passing `rails db:migrate:status` this command. 
The result was
```
database: db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20200122125436  Create articles
   up     20200122130324  Add description to articles
   up     20200331035710  Create users
   up     20200402132442  Add user id to articles
   up     20200411091702  Add password digest to users

```

**Comment by ansary14-zz** [comment]
Here is **`schema.rb`** Screenshot.
![Screenshot from 2020-06-12 19-59-31](https://user-images.githubusercontent.com/33208962/84510830-7646dd80-ace7-11ea-9785-4e00a35ccdf1.png)

**Comment by ansary14-zz** [comment]
I think I need to add data into **articles** and **users** table. 
Like `Article.create`
Using `rails console`

**Comment by wasifhossain** [comment]
exactly!

in case you have setup your OS from fresh, then all your data are now gone, except if you had taken a backup of your disk.

so you need to insert data again
