### ISSUE TITLE
How to use this code in a if else case? (in a single dakota method)

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#77]
```rb
states = ["Kansas","Nebraska", "North Dakota", "South Dakota"]

def dakota(states)
  states.select {|state| state.include?("Dakota")}
end

def dakota(states)
    states.select {|state| state.split.length==2}
end

p dakota(states)
#Ansewer : ["North Dakota", "South Dakota"]
```

**Comment by wasifhossain** [comment]
sorry dont get the qn

**Comment by wasifhossain** [comment]
I think, the `dakota` method is supposed to return the items from the given array that contain the word `Dakota`. If there are NO words like that, then return those items that contain exactly 2 words after splitting the item.

the above could be transcribed as
```rb
def dakota(states)
  values = states.select { |state| state.include?('Dakota') }
  return values unless values.empty?

  states.select { |state| state.split.length == 2 }
end
```

**Comment by sadmanahmed** [comment]
if I want to use both conditions in a single method dakota for this question :
**Write two select functions that return the Dakotas: one using String#include? (Section 2.5) to test for the presence of the string “Dakota” and one that tests for the length of the split array being 2.**
