### ISSUE TITLE
Javascript not working 

### ISSUE THREAD

**Issue by ansary14-zz** [ormprog/rails_ama#79]
In my navigation bar, I have a drop-down menu. Name _Articles_.
**But now it's not working.**
When I click the dropdown menu its nothing show. but previously its show 3 options
![Screenshot from 2020-06-18 10-22-48](https://user-images.githubusercontent.com/33208962/84978022-b2e26100-b14d-11ea-8ab0-41e4f68f35b1.png)

My **`bootstrap`**, **`jquery`**, **`popper.js`** everything is fine.
Here is my `package.json` file screenshot
![Screenshot from 2020-06-18 10-21-53](https://user-images.githubusercontent.com/33208962/84977967-8cbcc100-b14d-11ea-95b5-0aed1988c4e6.png)

Here is the code of navigation dropdown class
![Screenshot from 2020-06-18 10-27-36](https://user-images.githubusercontent.com/33208962/84978300-5a5f9380-b14e-11ea-841d-035e7dc705c9.png)

**Comment by wasifhossain** [comment]
pls share Gemfile too

**Comment by wasifhossain** [comment]
also better if you can paste the content as `TEXT` instead of images. the problem with images is that in case we want to copy any lines relevant to the content, we can't do that on images

**Comment by wasifhossain** [comment]
also open the developer console and click on the Articles link on the navbar. share a small recording of the dev console

**Comment by ansary14-zz** [comment]
Here is the code of navigation dropdown class 

> </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Create new article", new_article_path, class: "dropdown-item" %>
          <%= link_to "View articles", articles_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to 'Log in', login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
      </li>

**Comment by ansary14-zz** [comment]
Here is Gemfile screesnshot

![Screenshot from 2020-06-18 12-30-54](https://user-images.githubusercontent.com/33208962/84986038-a6ff9a80-b15f-11ea-8332-e11b91532260.png)
![Screenshot from 2020-06-18 12-31-09](https://user-images.githubusercontent.com/33208962/84986048-a8c95e00-b15f-11ea-9940-28ef466e023c.png)

**Comment by ansary14-zz** [comment]
![Screenshot from 2020-06-18 12-36-05](https://user-images.githubusercontent.com/33208962/84986408-53da1780-b160-11ea-99f0-4fbfcd4ba790.png)

**Comment by ansary14-zz** [comment]
![Screenshot from 2020-06-18 12-37-17](https://user-images.githubusercontent.com/33208962/84986496-78ce8a80-b160-11ea-88f4-7bf152d338b4.png)

**Comment by wasifhossain** [comment]
are you running `rails server` in one shell and `./bin/webpack-dev-server` in another?

did you run `yarn` before running the above commands?

**Comment by wasifhossain** [comment]
also share the code how do you import **bootstrap** in your project

**Comment by ansary14-zz** [comment]
I'm running only `rails server` this command.

I didn't run `./bin/webpack-dev-server` this command before.

**Comment by ansary14-zz** [comment]
But when I am passing `./bin/webpack-dev-server` command 
It shows that

> ayub@ayub:~/railsproject/alpha-blog$ ./bin/webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/ayub/railsproject/alpha-blog/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: Hash: 195b4864c066b011027b
Version: webpack 4.41.5
Time: 304ms
Built at: 06/21/2020 8:23:31 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-9c2ee05924c217f48ad3.js   6.89 KiB  application  [emitted] [immutable]  application
js/application-9c2ee05924c217f48ad3.js.map   3.51 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ayub/railsproject/alpha-blog/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/ayub/railsproject/alpha-blog/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

ERROR in (webpack)-dev-server/client?http://localhost:3035
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ayub/railsproject/alpha-blog/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/ayub/railsproject/alpha-blog/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
ℹ ｢wdm｣: Failed to compile.

**Comment by ansary14-zz** [comment]
I didn't run `yarn` command before you **mention command**

**Comment by ansary14-zz** [comment]
I was set up **bootstrap** previously following this link
https://www.mashrurhossain.com/blog/rails6bootstrap4

**Comment by ansary14-zz** [comment]
@wasif vai any update with this situation.

**Comment by ansary14-zz** [comment]
I faced a hard time.
![Screenshot from 2020-06-21 19-45-16](https://user-images.githubusercontent.com/33208962/85226141-bf89e200-b3f7-11ea-8c32-00ce8226c0ff.png)

When I click the cross sign, it doesn't disappear!

**Comment by wasifhossain** [comment]
> are you running `rails server` in one shell and `./bin/webpack-dev-server` in another?
> 
> did you run `yarn` before running the above commands?

please follow the instructions and report further issues

Background:

using **webpacker** requires running **webpack-dev-server** in a separate process. and running `yarn` before running the dev server ensures that all javascript packages are installed listed in `package.json`

**Comment by ansary14-zz** [comment]
![Screenshot from 2020-06-21 21-52-16](https://user-images.githubusercontent.com/33208962/85229085-91150280-b409-11ea-9cfd-6928d2c045b4.png)

After following the above instruction, I send here my two-terminal screenshot.

All the red line errors I send you as a text format in earlier.

**Comment by wasifhossain** [comment]
great!

can you now paste the error msg from the right window **as text**

**Comment by ansary14-zz** [comment]
> ayub@ayub:~/railsproject/alpha-blog$ ./bin/webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/ayub/railsproject/alpha-blog/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: Hash: 195b4864c066b011027b
Version: webpack 4.41.5
Time: 304ms
Built at: 06/21/2020 8:23:31 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-9c2ee05924c217f48ad3.js   6.89 KiB  application  [emitted] [immutable]  application
js/application-9c2ee05924c217f48ad3.js.map   3.51 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ayub/railsproject/alpha-blog/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/ayub/railsproject/alpha-blog/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

ERROR in (webpack)-dev-server/client?http://localhost:3035
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ayub/railsproject/alpha-blog/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:497:9)
    at resolveExports (internal/modules/cjs/loader.js:513:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:641:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1016:27)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/ayub/railsproject/alpha-blog/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
ℹ ｢wdm｣: Failed to compile.

**Comment by wasifhossain** [comment]
can we see `app/javascript/packs/application.js`

**Comment by ansary14-zz** [comment]
Here is `app/javascript/packs/application.js` 

// This file is automatically compiled by Webpack, along with any other files
// present in this directory. You're encouraged to place your actual application logic in
// a relevant structure within app/javascript and only use these pack files to reference
// that code so it'll be compiled.

require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")


// Uncomment to copy all static images under ../images to the output folder and reference
// them with the image_pack_tag helper in views (e.g <%= image_pack_tag 'rails.png' %>)
// or the `imagePath` JavaScript helper below.
//
// const images = require.context('../images', true)
// const imagePath = (name) => images(name, true)

import "bootstrap"

**Comment by wasifhossain** [comment]
> I was set up **bootstrap** previously following this link
> https://www.mashrurhossain.com/blog/rails6bootstrap4

can you confirm if you have followed the link properly this time

**Comment by ansary14-zz** [comment]
Am I needing to set up bootstrap again?

**Comment by wasifhossain** [comment]
i mean just make sure that your code contain all the changes suggested by the link

**Comment by ansary14-zz** [comment]
I checked. Everything they suggested changes. I changed properly.
In previous, I didn't face this issue.

**Comment by wasifhossain** [comment]
whats your node version: `node -v`

**Comment by ansary14-zz** [comment]
v14.4.0

**Comment by wasifhossain** [comment]
oops. there has been a known issue with non-LTS node versions. latest node LTS is `v12.18.1`

where's node installed: `which node`

**Comment by ansary14-zz** [comment]
/usr/bin/node

**Comment by wasifhossain** [comment]
i see. can you reinstall above version and run `yarn` before webpack-dev-server

**Comment by ansary14-zz** [comment]
Am I run 
`sudo apt-get install curl
`
`curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`

or something else

**Comment by wasifhossain** [comment]
i think its better to use `NVM` to manage your node versions

can you first try https://github.com/ormprog/rails_ama/issues/80 and post nvm installation issues on that link

**Comment by wasifhossain** [comment]
also lets see the output of `yarn list @babel/core`

**Comment by wasifhossain** [comment]
feel free to reopen if you still have issues

**Comment by ansary14-zz** [comment]
I Installed `NVM`  
And my current `node -v` is `v12.18.1`


Here is output of this command `yarn list @babel/core` 
```

ayub@ayub-linux:~/alpha-blog$ yarn list @babel/core
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @babel/core@7.8.3
Done in 0.51s.
```

**Comment by ansary14-zz** [comment]
ayub@ayub-linux:~/alpha-blog$ ./bin/webpack-dev-server
ℹ ｢wds｣: Project is running at http://localhost:3035/
ℹ ｢wds｣: webpack output is served from /packs/
ℹ ｢wds｣: Content not from webpack is served from /home/ayub/alpha-blog/public/packs
ℹ ｢wds｣: 404s will fallback to /index.html
✖ ｢wdm｣: Hash: 0e1091a120f49cd77466
Version: webpack 4.41.5
Time: 243ms
Built at: 07/12/2020 8:32:29 PM
                                     Asset       Size       Chunks                         Chunk Names
    js/application-0ef682738b9646474bcb.js   6.81 KiB  application  [emitted] [immutable]  application
js/application-0ef682738b9646474bcb.js.map   3.51 KiB  application  [emitted] [dev]        application
                             manifest.json  364 bytes               [emitted]              

ERROR in ./app/javascript/packs/application.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ayub/alpha-blog/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ayub/alpha-blog/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

ERROR in (webpack)-dev-server/client?http://localhost:3035
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/ayub/alpha-blog/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ayub/alpha-blog/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
ℹ ｢wdm｣: Failed to compile.

**Comment by wasifhossain** [comment]
make sure to back up the **yarn.lock** file somewhere outside the repo in case you need to refer to that file by any chance.

then remove it and rebuild the dependency by running `yarn`

finally follow https://github.com/ormprog/rails_ama/issues/79#issuecomment-647145128

**Comment by ansary14-zz** [comment]
After `yarn.lock` file remove outside the repository folder
I run `yarn`
After installing yarn 
I run `rails server` in one terminal and run `./bin/webpack-dev-server` in another

Now everything is fine.

**Comment by ansary14-zz** [comment]
`./bin/webpack-dev-server` Is this command needed everytime alongside `rails server`?

**Comment by wasifhossain** [comment]
> `./bin/webpack-dev-server` Is this command needed everytime alongside `rails server`?

YES
