### ISSUE TITLE
How to delete a git branch without harming the master branch?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#8]
Should I follow the steps:
1. Shift to master by 
```
git checkout master
```
2. the delete the branch
``` 
git branch -d <branch_name> 
```

Is this the right command?

**Comment by sadmanahmed** [comment]
Should I follow the steps:
1. Shift to master by 
```
git checkout master
```
2. the delete the branch
``` 
git branch -d <branch_name> 
```

Is this the right command?

**Comment by wasifhossain** [comment]
deleting a local branch requires capital D:
```sh
git branch -D <branch-name>
```

**Comment by sadmanahmed** [comment]
okay ,following the steps.

**Comment by wasifhossain** [comment]
please reopen it if you still have issues regarding the topic
