### ISSUE TITLE
why the output is showing 1..10

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#81]
```
class Rubyconf

  def any_are_odd(n)
    n.each {|n|  p n.odd?}
  end
end

b = Rubyconf.new
a = 1..10

puts b.any_are_odd(a)

```
result
```
true
false
true
false
true
false
true
false
true
false
1..10
```

**Comment by wasifhossain** [comment]
in Ruby, the `return` keyword is **optional** in methods

and a method always returns the value of the last executed statement inside the method

for the above case, `n.each {|n|  p n.odd?}` is the last stmt that would be executed. as `each` method does not return any value, so the method returns the value of `n`, which is `1..10`

**Comment by sadmanahmed** [comment]
and how to solve it(not show 1..10)?

**Comment by wasifhossain** [comment]
you can't do it. it works this way when you run the code in console. 

but you don't need to worry about that extra line of output. its ignored in actual code
