### ISSUE TITLE
how this 2 functions are working ? 

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#82]
(I know about n.any?(&:odd?) as it as n.any? {|n| n.odd?})
But how these are working and also `value` attributes is not changing its value from nil. and I thought it will return the odd values   
```
class Rubyconf
  def any_are_odd(n)
    n.any?(&:odd?)
  end
  def any_are_odd1(n)
    n.any? {|key,value| key==value}
  end

end

b = Rubyconf.new
a = 1..10

puts b.any_are_odd(a)
#true
puts b.any_are_odd1(a)
#false
```

**Comment by wasifhossain** [comment]
`any?` method yields each element to the given block and checks if the block results in `true` for at least 1 of the elements

**Comment by wasifhossain** [comment]
there is a problem with `n.any? {|key,value| key==value}`, as each element of `1..10` here is just a number; not a tuple (key/value pair). so `value` would always be `nil` for each element of `n`

**Comment by sadmanahmed** [comment]
yes that is my query .. Micheal hartl in his enumerable video shows this something but didnot understand why he is doing that

**Comment by sadmanahmed** [comment]
Okay I will closing it for now.
