### ISSUE TITLE
params in controller actions

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#85]
```
def create
  @user = User.find_by_email(params[:session][:email])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to '/'
  else
    redirect_to 'login'
  end 
end
``` 
I am a bit cofused in the 2nd and 3rd line **Params** .
And is **find_by_email** an enumerable like find but have not **find** it in ruby doc module section

**Comment by wasifhossain** [comment]
`params` is a method that is **accessible inside all controller actions**. it returns an instance of [`ActionController::Parameters`](https://api.rubyonrails.org/classes/ActionController/Parameters.html)

**Comment by sadmanahmed** [comment]
actually confused with the (params[:session][:email]) and  params[:session][:password]).

I understood @book = Book.find(params[:id]) but geting confused with 2 attributes in the params.

**Comment by wasifhossain** [comment]
if you use binding.pry around that line and check its value, you would be able to answer what these mean yourself. the doc link in my earlier post would help you how you can access the attributes in params.

basically, params works like a hash. so you can access params' keys the same way that you would do with a hash
