### ISSUE TITLE
what is "||=" ?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#86]
```
helper_method :current_user 
def current_user 
  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
end 
```
may ik what this operator means ||= ? Ik about ||
Ik a=+1 means a= a+1, is that something like that?

**Comment by sadmanahmed** [comment]
Found it on net but failed to understand https://stackoverflow.com/questions/995593/what-does-or-equals-mean-in-ruby

**Comment by sadmanahmed** [comment]
another link https://www.ruby-forum.com/t/the-definitive-list-of-or-equal-threads-and-pages/136446

**Comment by wasifhossain** [comment]
it's a mix of operator and assignment in Ruby, called **abbreviated assignment**: https://ruby-doc.org/core-2.7.1/doc/syntax/assignment_rdoc.html#label-Abbreviated+Assignment

`a ||= b` can be broken down to: `a || (a = b)`

which reads as, return `a` if `a` is truthy, else assign `a` to `b` before returning

**Comment by sadmanahmed** [comment]
Sorry, I Don't get it

**Comment by wasifhossain** [comment]
try to apply the above logic in the following example
```rb
class A
  def initialize(val = nil)
    @a = val
  end
  
  def test(val)
    @a ||= val
  end
end

obj1 = A.new(100)
obj1.test(48) # 100

obj2 = A.new
obj2.test(48) # 48
```

**Comment by sadmanahmed** [comment]
But what will happens 
obj1 = A.new(100)
obj1.test(100) # is it will be 100,right?
so it will compare the value and return the original value?
and if the will no value assigned ,it will assign a value?

**Comment by wasifhossain** [comment]
in another way, a ||= b can be read as
```rb
if a
 a
else
 a = b
end
```

**Comment by sadmanahmed** [comment]
So my thought is right? If anything assigned already it is okay, but if nothing assigned then a new value can be assigned, right?

**Comment by wasifhossain** [comment]
"anything assigned" **won't** work. it should be said as "any **truthy** value assigned"

e.g

a = false
b = nil
here `a` is assigned to `false` and `b` holds `nil`. both `a` and `b` are assigned, but none of them are truthy.

**in Ruby, any value is TRUTHY, except `false` and `nil`**

to check if a value is truthy/falsey, use `!!` as prefix
```rb
!!100 # true
!!false # false
!!nil # false
```

**Comment by sadmanahmed** [comment]
Oh,okay ...
