### ISSUE TITLE
Why do we define methods and helper methods in the application_controller.rb? Is it like available for everyone, that is why? 

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#88]

**Comment by wasifhossain** [comment]
likely the case. in general, all controllers are inherited from ApplicationController. so defining a method in the ancestor class makes it available in all descendent classes

**Comment by sadmanahmed** [comment]
Got it , I also think like that .
What about the helper_method?

**Comment by wasifhossain** [comment]
the general trick while working in Ruby/Rails or any other programming environment is to consult with the official api documentation.

Ruby: https://ruby-doc.org/core-2.7.1/ (latest version as of writing)
Rails: https://api.rubyonrails.org/

`helper_method` is a rails api: https://api.rubyonrails.org/classes/AbstractController/Helpers/ClassMethods.html#method-i-helper_method
