### ISSUE TITLE
How the nested loop is working

### ISSUE THREAD

**Issue by wasifhossain** [ormprog/rails_ama#89]
```rb
s = [['ham', 'swiss'], ['turkey', 'cheddar'], ['roast beef', 'gruyere']]
s.each { |sub_array| sub_array.each { |element| puts element } }
```

**Comment by wasifhossain** [comment]
let's break the array down to understand how the elements of it are processed by the `each` iterators
```rb
[
  ['ham', 'swiss'],            # <-- outer each, iteration 0, assigned to 'sub_array'
  ['turkey', 'cheddar'],       # <-- outer each, iteration 1, assigned to 'sub_array'
  ['roast beef', 'gruyere']    # <-- outer each, iteration 2, assigned to 'sub_array'
]


[
  'ham',   # inner each, iteration 0, assigned to 'element'
  'swiss'  # inner each, iteration 1, assigned to 'element'
]
```

**Comment by wasifhossain** [comment]
for `['ham', 'swiss']`, `puts element` is printing it out like this
```
ham
swiss
```
same goes for the other `sub_array`s

**Comment by wasifhossain** [comment]
if you don't print the value inside an `each` block, you won't see any output, as `each` method merely iterates over a collection of items.

you are responsible for doing whatever you want with each item in an `each` block

**Comment by wasifhossain** [comment]
let me know if you have further questions

**Comment by ahadrajnomore** [comment]
Got it. Thanks  a lot.
