### ISSUE TITLE
So for making the methods available in view, that is the sole purpose of helper_method?

### ISSUE THREAD

**Issue by sadmanahmed** [ormprog/rails_ama#90]
helper_method(*meths)Link
Declare a controller method as a helper. For example, the following makes the current_user and logged_in? controller methods available to the view:
```
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find_by(id: session[:user])
  end
  def logged_in?
    current_user != nil
  end
end

In a view:
<% if logged_in? -%>Welcome, <%= current_user.name %><% end -%>
```

**Comment by wasifhossain** [comment]
yes. its used to make any "controller" methods available to some view, be it a public method or private

**Comment by sadmanahmed** [comment]
Do we need to use this in only Application_controller or in every place from where we pick a method to see then in view?

**Comment by wasifhossain** [comment]
depends on which view you want to access the method from. e.g. if you want some method accessible from any views, then the best place is to use the helper_method at the top level controller, which is `ApplicationController` in most cases
